function tomlString(value: string): string {
  return JSON.stringify(value);
}

export function buildTaskCodexConfig(args: {
  model: string;
  endpointProxyBase: string;
  wireApi: 'responses' | 'chat';
  userBearerToken?: string;
}): string {
  const lines: string[] = [
    '# Generated by @mbos/agent-codex-runner for this task workspace.',
    '# Project-scoped Codex config loaded from <cwd>/.codex/config.toml',
    `model = ${tomlString(args.model)}`,
    'model_provider = "proxy"',
    '',
    '# Reduce unsupported built-in tool usage for OpenAI-compatible third-party providers.',
    'web_search = "disabled"',
    '# Keep notebook output compact; reasoning is still available in tool/provider responses when needed.',
    'hide_agent_reasoning = true',
    '',
    '[model_providers.proxy]',
    `name = ${tomlString('Proxy')}`,
    `base_url = ${tomlString(args.endpointProxyBase)}`,
    `wire_api = ${tomlString(args.wireApi)}`,
  ];
  if (args.userBearerToken && args.userBearerToken.trim().length > 0) {
    lines.push(`experimental_bearer_token = ${tomlString(args.userBearerToken)}`);
  }
  return `${lines.join('\n')}\n`;
}

export function buildCodexExecArgs(args: {
  model: string;
  prompt: string;
  cwd: string;
  endpointProxyBase: string;
  wireApi: 'responses' | 'chat';
  userBearerToken?: string;
  resumeLast?: boolean;
  yolo?: boolean;
}): string[] {
  const cliArgs = [
    'exec',
    '--skip-git-repo-check',
    '--json',
    '--model',
    args.model,
    '-c',
    'model_provider="proxy"',
    '-c',
    'model_providers.proxy.name="Proxy"',
    '-c',
    `model_providers.proxy.base_url=${JSON.stringify(args.endpointProxyBase)}`,
    '-c',
    `model_providers.proxy.wire_api=${JSON.stringify(args.wireApi)}`,
    '-c',
    'project_root_markers=[]',
    '-c',
    `projects.${JSON.stringify(args.cwd)}.trust_level="trusted"`,
    '-c',
    'web_search="disabled"',
    '-c',
    'hide_agent_reasoning=true',
  ];
  if (args.yolo) {
    cliArgs.splice(1, 0, '--dangerously-bypass-approvals-and-sandbox');
  } else {
    cliArgs.splice(1, 0, '--full-auto');
  }
  if (args.userBearerToken && args.userBearerToken.trim().length > 0) {
    cliArgs.push(
      '-c',
      `model_providers.proxy.experimental_bearer_token=${JSON.stringify(args.userBearerToken)}`,
    );
  }
  if (args.resumeLast) {
    cliArgs.splice(1, 0, 'resume', '--last');
  }
  cliArgs.push(args.prompt);
  return cliArgs;
}

