import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { TaskWorkspacePaths } from './task-workspace.js';

export type NotebookTaskInput = {
  kind?: 'library_object' | 'artifact' | 'url';
  library_id?: string;
  key?: string;
  task_id?: string;
  artifact_id?: string;
  task_relative_path?: string;
  url?: string;
  imported_library_id?: string;
  imported_key?: string;
  filename?: string;
  file_type?: string;
  file_size?: number;
};

export type NotebookExecutionContext = {
  task_id?: string;
  run_id?: string;
  workspace_binding_mode?: 'file_library' | 'pre_mounted';
};

type NotebookAssetDebugLog = (message: string, extra?: Record<string, unknown>) => void;

export function buildNotebookHeadlessPreamble(args: {
  artifactsDir: string;
}): string {
  return [
    'Notebook execution policy (headless execution):',
    '- This environment is headless. Do not open GUI windows or interactive viewers.',
    '- Do not call blocking UI display operations such as matplotlib plt.show().',
    `- Save charts/images/files to the artifacts directory: ${args.artifactsDir}`,
    '- Put final textual conclusions in your response; put generated files in artifacts.',
    '',
    'Use files already present in the workspace to complete the user request and mention generated artifact filenames in your final response.',
    '',
  ].join('\n');
}

function buildNotebookAgentsMd(): string {
  return [
    '# AGENTS.md (generated by @mbos/agent-codex-runner)',
    '',
    '## Notebook Execution Rules (Mandatory)',
    '',
    '1. This task runs in a headless environment. Do not open GUI windows or interactive viewers.',
    '2. Do not call blocking display APIs (for example: matplotlib.pyplot.show()).',
    '3. Save generated files/charts/images into `./.artifacts/`.',
    '4. Put final conclusions in the response message, and mention generated artifact filenames.',
    '5. This workspace root is the persistent notebook environment for this task.',
    '6. `HOME` is the same directory as the current workspace root (`cwd`). Keep all dynamic state inside this home directory.',
    '7. Builtin skills are installed under `~/.agents/skills` for this task. Do not rely on `/etc/codex` for mutable runtime state.',
    '8. Use the `mbos-context` builtin skill for user/task context, simple credentials, and shared guidance instead of browsing workspace files for hidden config.',
    '9. Managed OAuth credentials such as Feishu stay in AgentSmith-managed connections and are exposed through read-only context views like `managed_credentials.feishu`.',
    '10. If you need Python / Node / Rust tools or libraries, install them in user mode only so they stay inside the current home directory.',
    '11. Never write dynamic config, package installs, caches, or auth material outside the current home/workspace root.',
    '',
    '## Output Convention',
    '',
    '- Text summary -> final response message',
    '- Files/images -> `./.artifacts/` (system will collect these as notebook artifacts)',
    '- AgentSmith runner state -> `./.mbos/`',
    '- Codex runtime state -> `./.codex/`',
    '- Builtin + user skills -> `./.agents/skills/`',
    '- Agent-facing persistent context -> use `mbos-context` rather than hidden workspace files',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: use user installs rooted at `~/.local` (for example `python3 -m pip install --user ...`).',
    '- Node: use a user prefix rooted at `~/.local` and avoid global/system installs.',
    '- Rust: use `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup` inside this workspace home.',
    '- Prefer commands that keep binaries under `~/.local/bin` or `~/.cargo/bin`.',
    '',
  ].join('\n');
}

function buildRunnerRuntimeMd(): string {
  return [
    '# RUNNER_RUNTIME.md (generated by @mbos/agent-codex-runner)',
    '',
    '## Runtime Contract',
    '',
    '- `HOME == cwd`; the current task workspace root is the persistent home directory.',
    '- All dynamic configuration, caches, package installs, toolchains, and mutable auth material must stay under this home directory.',
    '- Builtin skills are installed under `~/.agents/skills`.',
    '- Agent-facing user/task/project/workspace context is provided through the `mbos-context` builtin skill and AgentSmith Context Store APIs.',
    '- Managed OAuth credentials are exposed as read-only context entries such as `managed_credentials.feishu`.',
    '- Codex runtime state is stored under `~/.codex`.',
    '- Notebook output files belong in `~/.artifacts`.',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: install with user mode rooted at `~/.local`.',
    '- Node: install with a user prefix rooted at `~/.local`.',
    '- Rust: keep `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup`.',
    '- Never write mutable runtime state to `/etc`, `/usr/local`, `/opt`, or shared system directories.',
    '',
  ].join('\n');
}

export async function prepareNotebookWorkspaceAssets(args: {
  cwd: string;
  paths: TaskWorkspacePaths;
  executionContext: NotebookExecutionContext;
  taskInputs: NotebookTaskInput[];
  debugLog?: NotebookAssetDebugLog;
}): Promise<{
  artifactsDir: string;
}> {
  const { cwd, paths, executionContext, taskInputs, debugLog } = args;
  const artifactsDir = paths.artifactsDir;
  await withFsOpTimeout(
    'notebook_assets_mkdir_mbos',
    mkdir(paths.mbosDir, { recursive: true }),
    debugLog,
    { cwd, target: paths.mbosDir },
  );
  await withFsOpTimeout(
    'notebook_assets_mkdir_artifacts',
    mkdir(artifactsDir, { recursive: true }),
    debugLog,
    { cwd, target: artifactsDir },
  );
  debugLog?.('notebook_assets_inputs_ignored', {
    cwd,
    task_inputs_count: taskInputs.length,
  });
  const agentsPath = join(cwd, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    await withFsOpTimeout(
      'notebook_assets_write_agents_md',
      writeFile(agentsPath, buildNotebookAgentsMd(), 'utf-8'),
      debugLog,
      { cwd, target: agentsPath, workspace_binding_mode: executionContext.workspace_binding_mode ?? null },
    );
  }
  const runtimeContractPath = join(paths.mbosDir, 'RUNNER_RUNTIME.md');
  await withFsOpTimeout(
    'notebook_assets_write_runner_runtime_md',
    writeFile(runtimeContractPath, buildRunnerRuntimeMd(), 'utf-8'),
    debugLog,
    { cwd, target: runtimeContractPath },
  );
  return { artifactsDir };
}

async function withFsOpTimeout<T>(
  name: string,
  promise: Promise<T>,
  debugLog?: NotebookAssetDebugLog,
  extra?: Record<string, unknown>,
): Promise<T> {
  const timeoutMs = Number.parseInt(process.env.MBOS_NOTEBOOK_ASSET_IO_TIMEOUT_MS ?? '30000', 10);
  const startedAt = Date.now();
  debugLog?.(`${name}_start`, extra);
  let timer: NodeJS.Timeout | undefined;
  try {
    const result = await Promise.race<T>([
      promise,
      new Promise<T>((_resolve, reject) => {
        timer = setTimeout(() => {
          reject(new Error(`${name}_timeout_after_${String(timeoutMs)}ms`));
        }, timeoutMs);
      }),
    ]);
    debugLog?.(`${name}_done`, {
      ...extra,
      duration_ms: Date.now() - startedAt,
    });
    return result;
  } finally {
    if (timer) clearTimeout(timer);
  }
}
