import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { TaskWorkspacePaths } from './task-workspace.js';

export type NotebookTaskInput = {
  kind?: 'library_object' | 'artifact' | 'url';
  library_id?: string;
  key?: string;
  task_id?: string;
  artifact_id?: string;
  task_relative_path?: string;
  url?: string;
  imported_library_id?: string;
  imported_key?: string;
  filename?: string;
  file_type?: string;
  file_size?: number;
};

export type NotebookExecutionContext = {
  task_id?: string;
  run_id?: string;
  workspace_binding_mode?: 'file_library' | 'pre_mounted';
};

type NotebookAssetDebugLog = (message: string, extra?: Record<string, unknown>) => void;

export function buildNotebookHeadlessPreamble(args: {
  artifactsDir: string;
}): string {
  return [
    'Notebook execution policy (headless execution):',
    '- This environment is headless. Do not open GUI windows or interactive viewers.',
    '- Do not call blocking UI display operations such as matplotlib plt.show().',
    `- Save charts/images/files to the artifacts directory: ${args.artifactsDir}`,
    '- Put final textual conclusions in your response; put generated files in artifacts.',
    '',
    'Use files already present in the workspace to complete the user request and mention generated artifact filenames in your final response.',
    '',
  ].join('\n');
}

function buildNotebookAgentsMd(): string {
  return [
    '# AGENTS.md (generated by @mbos/agent-codex-runner)',
    '',
    '## Notebook Execution Rules (Mandatory)',
    '',
    '1. This task runs in a headless environment. Do not open GUI windows or interactive viewers.',
    '2. Do not call blocking display APIs (for example: matplotlib.pyplot.show()).',
    '3. Save generated files/charts/images into `./.artifacts/`.',
    '4. Put final conclusions in the response message, and mention generated artifact filenames.',
    '5. This workspace root is the persistent notebook environment for this task.',
    '',
    '## Output Convention',
    '',
    '- Text summary -> final response message',
    '- Files/images -> `./.artifacts/` (system will collect these as notebook artifacts)',
    '',
  ].join('\n');
}

export async function prepareNotebookWorkspaceAssets(args: {
  cwd: string;
  paths: TaskWorkspacePaths;
  executionContext: NotebookExecutionContext;
  taskInputs: NotebookTaskInput[];
  debugLog?: NotebookAssetDebugLog;
}): Promise<{
  artifactsDir: string;
}> {
  const { cwd, paths, executionContext, taskInputs, debugLog } = args;
  const artifactsDir = paths.artifactsDir;
  await withFsOpTimeout(
    'notebook_assets_mkdir_artifacts',
    mkdir(artifactsDir, { recursive: true }),
    debugLog,
    { cwd, target: artifactsDir },
  );
  debugLog?.('notebook_assets_inputs_ignored', {
    cwd,
    task_inputs_count: taskInputs.length,
  });
  const agentsPath = join(cwd, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    await withFsOpTimeout(
      'notebook_assets_write_agents_md',
      writeFile(agentsPath, buildNotebookAgentsMd(), 'utf-8'),
      debugLog,
      { cwd, target: agentsPath, workspace_binding_mode: executionContext.workspace_binding_mode ?? null },
    );
  }
  return { artifactsDir };
}

async function withFsOpTimeout<T>(
  name: string,
  promise: Promise<T>,
  debugLog?: NotebookAssetDebugLog,
  extra?: Record<string, unknown>,
): Promise<T> {
  const timeoutMs = Number.parseInt(process.env.MBOS_NOTEBOOK_ASSET_IO_TIMEOUT_MS ?? '30000', 10);
  const startedAt = Date.now();
  debugLog?.(`${name}_start`, extra);
  let timer: NodeJS.Timeout | undefined;
  try {
    const result = await Promise.race<T>([
      promise,
      new Promise<T>((_resolve, reject) => {
        timer = setTimeout(() => {
          reject(new Error(`${name}_timeout_after_${String(timeoutMs)}ms`));
        }, timeoutMs);
      }),
    ]);
    debugLog?.(`${name}_done`, {
      ...extra,
      duration_ms: Date.now() - startedAt,
    });
    return result;
  } finally {
    if (timer) clearTimeout(timer);
  }
}
