import type { JsonDocStorePort } from '@mbos/ports';
import { listUserExternalConnections } from './user-external-connections-store.js';
import { getWorkspaceFeishuIntegration } from './workspace-feishu-settings-store.js';

export type ExecutionContextFile = {
  relative_path: string;
  content: string;
  description?: string;
};

type ProviderConnectionSnapshot = {
  connection_id: string;
  display_name: string;
  note?: string | null;
  kind: string;
  status: string;
  workspace_id?: string | null;
  scopes?: string[] | null;
  expires_at?: string | null;
  last_refreshed_at?: string | null;
  fields: Record<string, string>;
};

function sanitizeProviderName(input: string): string {
  const trimmed = input.trim().toLowerCase();
  const safe = trimmed.replace(/[^a-z0-9._-]/g, '-');
  return safe || 'unknown';
}

function normalizeFieldMap(fields: Array<{ key: string; value: string }>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const field of fields) {
    const key = field.key.trim();
    if (!key) continue;
    out[key] = field.value;
  }
  return out;
}

function buildProviderCredentialFile(args: {
  userId: string;
  provider: string;
  connections: ProviderConnectionSnapshot[];
  taskId?: string;
}): ExecutionContextFile {
  const provider = sanitizeProviderName(args.provider);
  const credentialRoot = '.codex/credential';
  const relativePath = `${credentialRoot}/${provider}/connections.json`;
  const content = JSON.stringify(
    {
      schema_version: '1',
      generated_at: new Date().toISOString(),
      owner_user_id: args.userId,
      provider,
      description: 'User third-party account credentials grouped by provider. Values are provided for agent-side tool usage.',
      connections: args.connections,
    },
    null,
    2,
  );
  return {
    relative_path: relativePath,
    content,
    description: `credential bundle for provider ${provider}`,
  };
}

export async function buildThirdPartyCredentialFiles(
  docStore: JsonDocStorePort,
  userId: string,
  options?: { taskId?: string; workspaceId?: string },
): Promise<ExecutionContextFile[]> {
  const connections = await listUserExternalConnections(docStore, userId);
  if (connections.length === 0) {
    return [];
  }

  const effectiveConnections = selectEffectiveConnections(connections, options?.workspaceId);

  const grouped = new Map<string, ProviderConnectionSnapshot[]>();
  for (const connection of effectiveConnections) {
    const provider = sanitizeProviderName(connection.provider);
    const next: ProviderConnectionSnapshot = {
      connection_id: connection.id,
      display_name: connection.display_name,
      note: connection.note ?? null,
      kind: connection.kind,
      status: connection.status,
      workspace_id: connection.workspace_id ?? null,
      scopes: connection.scopes ?? null,
      expires_at: connection.expires_at ?? null,
      last_refreshed_at: connection.last_refreshed_at ?? null,
      fields: await buildConnectionFields(docStore, connection),
    };
    const bucket = grouped.get(provider);
    if (bucket) {
      bucket.push(next);
    } else {
      grouped.set(provider, [next]);
    }
  }

  const files: ExecutionContextFile[] = [];
  const indexItems: Array<{
    provider: string;
    relative_path: string;
    connection_count: number;
  }> = [];
  for (const [provider, providerConnections] of grouped.entries()) {
    const file = buildProviderCredentialFile({
      userId,
      provider,
      connections: providerConnections,
      taskId: options?.taskId,
    });
    files.push(file);
    indexItems.push({
      provider,
      relative_path: file.relative_path,
      connection_count: providerConnections.length,
    });
  }

  files.push({
    relative_path: '.codex/credential/index.json',
    description: 'index of generated credential files',
    content: JSON.stringify(
      {
        schema_version: '1',
        generated_at: new Date().toISOString(),
        owner_user_id: userId,
        description: 'Index of third-party credential files generated by AgentSmith.',
        files: indexItems.sort((a, b) => a.provider.localeCompare(b.provider)),
      },
      null,
      2,
    ),
  });

  return files.sort((a, b) => a.relative_path.localeCompare(b.relative_path));
}

function selectEffectiveConnections(
  connections: Awaited<ReturnType<typeof listUserExternalConnections>>,
  workspaceId?: string,
) {
  if (!workspaceId) {
    return connections;
  }
  const feishuForWorkspace = connections.filter(
    (connection) => connection.provider === 'feishu' && connection.workspace_id === workspaceId,
  );
  return connections.filter((connection) => {
    if (connection.provider !== 'feishu') {
      return true;
    }
    if (feishuForWorkspace.length > 0) {
      return connection.workspace_id === workspaceId;
    }
    return (connection.workspace_id ?? null) === null;
  });
}

async function buildConnectionFields(
  docStore: JsonDocStorePort,
  connection: Awaited<ReturnType<typeof listUserExternalConnections>>[number],
): Promise<Record<string, string>> {
  const fields = normalizeFieldMap(connection.fields);
  if (connection.provider !== 'feishu') {
    return fields;
  }
  if (!fields.app_id) {
    const envAppId = process.env.FEISHU_APP_ID?.trim();
    if (envAppId) {
      fields.app_id = envAppId;
    }
  }
  if (!fields.app_secret) {
    const envAppSecret = process.env.FEISHU_APP_SECRET?.trim();
    if (envAppSecret) {
      fields.app_secret = envAppSecret;
    }
  }
  if (!fields.feishu_mcp_endpoint) {
    const envMcp = process.env.FEISHU_MCP_ENDPOINT?.trim();
    if (envMcp) {
      fields.feishu_mcp_endpoint = envMcp;
    }
  }
  if (!fields.feishu_oauth_token_endpoint) {
    const envTokenEndpoint = process.env.FEISHU_OAUTH_TOKEN_URL?.trim();
    if (envTokenEndpoint) {
      fields.feishu_oauth_token_endpoint = envTokenEndpoint;
    }
  }
  if (!connection.workspace_id) {
    return fields;
  }
  const integration = await getWorkspaceFeishuIntegration(docStore, connection.workspace_id);
  if (!integration) {
    return fields;
  }
  if (!fields.app_id && integration.app_id.trim()) {
    fields.app_id = integration.app_id.trim();
  }
  if (!fields.app_secret && integration.app_secret?.trim()) {
    fields.app_secret = integration.app_secret.trim();
  }
  return fields;
}
