/** @type {import("tailwindcss").Config} */
module.exports = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./stories/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--bg-base) / <alpha-value>)",
        panel: "rgb(var(--bg-sidebar) / <alpha-value>)",
        surface: "rgb(var(--bg-surface) / <alpha-value>)",
        "surface-low": "rgb(var(--bg-surface-low) / <alpha-value>)",
        "surface-high": "rgb(var(--bg-surface-high) / <alpha-value>)",
        hover: "rgb(var(--bg-hover) / <alpha-value>)",
        foreground: "rgb(var(--text-strong) / <alpha-value>)",
        primary: "rgb(var(--text-primary) / <alpha-value>)",
        secondary: "rgb(var(--text-secondary) / <alpha-value>)",
        tertiary: "rgb(var(--text-tertiary) / <alpha-value>)",
        "icon-default": "rgb(var(--icon-default) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        error: "rgb(var(--error) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        dialog: "rgb(var(--bg-dialog) / <alpha-value>)",
        input: "rgb(var(--bg-input) / <alpha-value>)",
        "border-input": "rgb(var(--border-input) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        subtle: "rgb(var(--border-subtle) / <alpha-value>)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
      },
      spacing: {
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
      },
      fontFamily: {
        sans: ["var(--font-cursor-gothic)", "system-ui", "Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        serif: ["var(--font-jjannon)", "Iowan Old Style", "Palatino Linotype", "URW Palladio L", "P052", "ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
        mono: ["var(--font-berkeley-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        display: ["var(--font-cursor-gothic)", "system-ui", "Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        ui: ["system-ui", "-apple-system", "Segoe UI", "Helvetica Neue", "Arial", "sans-serif"],
      },
      boxShadow: {
        ambient: "var(--shadow-ambient)",
        card: "var(--shadow-card)",
        float: "var(--shadow-float)",
      },
      ringOffsetColor: {
        background: "rgb(var(--bg-base))",
        dialog: "rgb(var(--bg-dialog))",
      },
    },
  },
  plugins: [],
};
