import { homedir } from 'node:os';
import { resolve } from 'node:path';

export const OSS_REPO_NAME = 'agentsmith-oss';
export const OSS_GITHUB_REPO = 'lzjever/agentsmith-oss';
export const OSS_TARGET_DIR = resolve(homedir(), 'works/mbos-v1/agentsmith-oss');

export const ROOT_INCLUDE_FILES = [
  '.gitignore',
  '.node-version',
  '.nvmrc',
  'components.json',
  'eslint.config.mjs',
  'next-env.d.ts',
  'next.config.ts',
  'package-lock.json',
  'package.json',
  'postcss.config.js',
  'tailwind.config.js',
  'tsconfig.json',
] as const;

export const ROOT_INCLUDE_DIRS = [
  'assets',
  'infra',
  'messages',
  'packages',
  'public',
  'scripts',
  'src',
] as const;

export const ALWAYS_REMOVE_PATHS = [
  '.claude',
  '.github',
  '.infra',
  '.next',
  'artifacts',
  'docs',
  'e2e',
  'marketing',
] as const;

export const REMOVE_GLOBS = [
  '**/__tests__',
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.spec.ts',
  '**/*.spec.tsx',
  '**/vitest.config.ts',
  '**/playwright.config*.ts',
  '**/*.snap',
] as const;

export const PACKAGE_TEST_SCRIPT_NAMES = new Set([
  'test',
  'test:ui',
  'test:run',
  'test:coverage',
  'test:integration',
  'test:e2e',
  'test:e2e:all',
  'test:e2e:lane:mock:smoke',
  'test:e2e:lane:mock:chromium',
  'test:e2e:lane:mock:visual',
  'test:e2e:lane:mock:visual:update',
  'test:visual',
  'test:e2e:lane:mock:full:with-visual',
  'test:e2e:lane:backend-real',
  'test:e2e:integration:minimal',
  'test:e2e:integration:files',
  'test:e2e:integration:chat',
  'test:e2e:integration:agents',
  'test:e2e:integration:agents:chat',
  'test:e2e:integration:endpoints-capabilities',
  'test:e2e:integration:notebook',
  'test:e2e:integration:notebook:docker',
  'test:e2e:integration:files:mount-sync',
  'test:e2e:integration:chat:real',
  'test:e2e:integration:minimal:with-api',
  'test:e2e:integration:files:with-api',
  'test:e2e:integration:chat:with-api',
  'test:e2e:integration:agents:with-api',
  'test:e2e:integration:notebook-external:with-api',
  'test:e2e:integration:endpoints-capabilities:with-api',
  'test:e2e:integration:chat:real:with-api',
  'test:default-e2e',
  'test:backend-real:core',
  'test:governance',
  'test:notebook:backend-real:smoke',
  'test:internal:backend-real:notebook-workspace',
  'test:agents:backend-real:runner',
  'test:files:backend-real:smoke',
  'test:files:backend-real:sync',
  'test:files:backend-real:ui-sync',
  'test:files:release:strict',
  'test:visual:backend-real:review',
  'test:release:precheck',
  'test:demo-bundle:inputs',
  'test:cluster-bundle:inputs',
  'test:demo-rendered-env',
  'test:cluster-rendered-env',
  'test:client-public-runtime',
  'test:e2e:ui',
  'test:e2e:debug',
  'gate:fast',
  'gate:default',
  'gate:release',
  'lane:mock',
  'lane:visual',
  'lane:backend-real:core',
  'lane:backend-real:release',
  'manual:feishu:admin',
  'manual:feishu:user',
  'manual:feishu:check',
  'backend-real:reset',
  'backend-real:bootstrap',
  'backend-real:ready',
  'backend-real:run',
  'backend-real:report',
  'integration:deps:up',
  'integration:deps:up:env',
  'integration:deps:down',
  'integration:deps:down:volumes',
  'integration:deps:logs',
  'integration:deps:ps',
  'integration:deps:init:postgres',
  'integration:deps:init:keycloak',
  'integration:deps:smoke',
  'integration:test:adapters',
  'contracts:check-limit-naming',
  'contracts:check-current-workflows',
  'contracts:check-engineering-governance',
  'contracts:check',
  'contracts:check-doc-governance',
  'contracts:check-openapi-core',
  'contracts:check-openapi-route-kinds',
  'contracts:check-openapi-breaking',
  'contracts:check-openapi',
  'storybook',
  'build-storybook',
  'openapi:check-generated',
  'governance:report',
  'current-workflow:sync',
  'current-workflow:check',
] as const);

export const KEEP_ROOT_SCRIPTS = {
  dev: 'bash scripts/run-next-dev-safe.sh --turbopack',
  'dev:test': 'bash scripts/run-next-dev-safe.sh',
  build: 'next build',
  start: 'next start',
  lint: 'eslint . --max-warnings=0',
  'ws:typecheck': 'npm run --workspaces typecheck --if-present',
  'ws:build': 'npm run --workspaces build --if-present',
  'demo:bundle': 'bash scripts/demo-deploy/build-offline-bundle.sh',
  'demo:prepare': 'bash scripts/demo-deploy/prepare.sh',
  'demo:deploy': 'bash scripts/demo-deploy/deploy.sh',
  'demo:bootstrap': 'bash scripts/demo-deploy/bootstrap.sh',
  'cluster:bundle': 'bash scripts/cluster-deploy/build-bundle.sh',
  'cluster:prepare': 'bash scripts/cluster-deploy/prepare.sh',
  'cluster:publish-images': 'bash scripts/cluster-deploy/publish-images.sh',
  'cluster:deploy-substrate': 'bash scripts/cluster-deploy/deploy-substrate.sh',
  'cluster:deploy-app': 'bash scripts/cluster-deploy/deploy-app.sh',
  'cluster:apply-cluster-prereqs': 'bash scripts/cluster-deploy/apply-cluster-prereqs.sh',
  'cluster:deploy-sandbox': 'bash scripts/cluster-deploy/deploy-sandbox.sh',
  'cluster:deploy': 'bash scripts/cluster-deploy/deploy.sh',
  'cluster:bootstrap': 'bash scripts/cluster-deploy/bootstrap.sh',
  'docker:app': 'docker build -f infra/deploy/Dockerfile.agentsmith-app-base -t agentsmith-app-base:oss . && docker build --build-arg APP_BASE_IMAGE=agentsmith-app-base:oss -f infra/deploy/Dockerfile.agentsmith-app -t agentsmith-app:oss .',
  'docker:runner': 'docker build -f infra/runner/Dockerfile.notebook-codex-runner-base -t agentsmith-notebook-codex-runner-base:oss . && docker build --build-arg RUNNER_BASE_IMAGE=agentsmith-notebook-codex-runner-base:oss -f infra/runner/Dockerfile.notebook-codex-runner -t agentsmith-notebook-codex-runner:oss .',
} as const;

export const REMOVE_ROOT_DEV_DEPENDENCIES = new Set([
  '@playwright/test',
  '@storybook/addon-essentials',
  '@storybook/addon-interactions',
  '@storybook/addon-themes',
  '@storybook/nextjs',
  '@storybook/react',
  '@storybook/test',
  '@testing-library/jest-dom',
  '@testing-library/react',
  '@testing-library/user-event',
  '@vitest/coverage-v8',
  '@vitest/ui',
  'jsdom',
  'msw',
  'msw-storybook-addon',
  'openapi-diff',
  'storybook',
  'vitest',
] as const);

export const KEEP_SCRIPT_DIR_PATTERNS = [
  'scripts/run-next-dev-safe.sh',
  'scripts/run-external-runner-dev.sh',
  'scripts/demo-deploy/**',
  'scripts/cluster-deploy/**',
  'scripts/lib/**',
  'scripts/models/sync-catalog.ts',
] as const;

export const REMOVE_SCRIPT_DIR_PATTERNS = [
  'scripts/**/__tests__/**',
  'scripts/contracts/**',
  'scripts/governance/**',
  'scripts/local-manual/**',
  'scripts/integration-*',
  'scripts/run-integration-*',
  'scripts/run-internal-*',
  'scripts/run-file-library-real-gate.sh',
  'scripts/notebook-*',
  'scripts/governance-*',
  'scripts/backend-real*',
  'scripts/preprod-*',
  'scripts/manual-*',
  'scripts/feishu-real-*',
  'scripts/workspace-*-gate.sh',
  'scripts/*smoke*',
  'scripts/*benchmark*',
  'scripts/*baseline*',
  'scripts/write-*-evidence.js',
  'scripts/generate-doc-artifacts.sh',
  'scripts/generate-marketing-assets.sh',
] as const;

export const KEEP_DOC_PATHS = [
  'docs/README.md',
] as const;

export const REMOVE_PUBLIC_TEXT_PATTERNS = [
  'backend-real',
  'governance',
  'local-manual',
  'rehearsal',
  'incident',
  'gate:',
] as const;
