import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import YAML from 'yaml';

type GenerateTypesOptions = {
  input: string;
  outputPath?: string;
};

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../..');

function resolveRepoPath(targetPath: string): string {
  if (path.isAbsolute(targetPath)) {
    return targetPath;
  }
  const direct = path.resolve(REPO_ROOT, targetPath);
  if (existsSync(direct)) {
    return direct;
  }
  if (targetPath === 'openapi.yaml' || targetPath === 'openapi.yml' || targetPath === 'openapi.json') {
    return path.resolve(REPO_ROOT, 'docs/contracts/specs', targetPath);
  }
  return direct;
}

async function loadSpec(inputPath: string): Promise<unknown> {
  const content = await readFile(inputPath, 'utf-8');
  const ext = path.extname(inputPath).toLowerCase();
  if (ext === '.yaml' || ext === '.yml') {
    return YAML.parse(content) as unknown;
  }
  return JSON.parse(content) as unknown;
}

export async function generateTypes({ input, outputPath = 'src/lib/api/types.generated.ts' }: GenerateTypesOptions) {
  const absInput = resolveRepoPath(input);
  const absOutput = resolveRepoPath(outputPath);
  const schema = await loadSpec(absInput);
  const generated = await openapiTS(schema as Parameters<typeof openapiTS>[0], {
    alphabetize: true,
  });
  const content = typeof generated === 'string' ? generated : astToString(generated);
  return {
    outputPath,
    content: `/* eslint-disable */\n/* This file is auto-generated by scripts/openapi/generate-types.ts */\n\n${content}`,
    absOutput,
  };
}

async function main(): Promise<void> {
  const input = process.argv[2] ?? 'docs/contracts/specs/openapi.yaml';
  const outputPath = process.argv[3] ?? 'src/lib/api/types.generated.ts';
  const generated = await generateTypes({ input, outputPath });
  await writeFile(generated.absOutput, generated.content, 'utf-8');
  process.stdout.write(`[openapi] generated ${generated.outputPath} from ${input}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  void main();
}
