#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"
init_local_manual_env

wait_port_free "${PORT_API}" "api" 30
launch_detached "${API_PID_FILE}" "${API_LOG}" "
  cd '${ROOT_DIR}' && \
  export PORT='${PORT_API}' \
    KEYCLOAK_BASE_URL='${KEYCLOAK_BASE_URL}' \
    KEYCLOAK_REALM='${KEYCLOAK_REALM}' \
    AGENT_RUNNER_DEVELOPER_EXECUTION_HTTP_BASE_URL='http://localhost:${PORT_API}' \
    MBOS_AGENT_TASK_DEVELOPER_WORKSPACE_ROOT='${MBOS_AGENT_TASK_DEVELOPER_WORKSPACE_ROOT}' \
    AGENT_EXECUTION_HTTP_BASE_URL='${AGENT_EXECUTION_HTTP_BASE_URL:-http://localhost:${PORT_API}}' \
    PUBLIC_WEB_BASE_URL='http://localhost:${PORT_WEB}' \
    PUBLIC_API_BASE_URL='http://localhost:${PORT_API}' \
    AGENT_EXECUTION_WS_BASE_URL='${AGENT_EXECUTION_WS_BASE_URL:-}' \
    ASBCP_INTERNAL_BASE_URL='${ASBCP_INTERNAL_BASE_URL:-}' \
    ASBCP_SERVICE_KEY='${ASBCP_SERVICE_KEY:-}' \
    INTERNAL_AGENT_K8S_NAMESPACE='${INTERNAL_AGENT_K8S_NAMESPACE:-}' \
    INTERNAL_AGENT_IMAGE='${INTERNAL_AGENT_IMAGE:-}' \
    INTEGRATION_INTERNAL_AGENT_IMAGE='${INTEGRATION_INTERNAL_AGENT_IMAGE:-}' \
    MANAGED_RUNNER_IMAGE='${MANAGED_RUNNER_IMAGE:-}' \
    AFSCP_BASE_URL='${AFSCP_BASE_URL:-}' \
    AFSCP_CALLER_SERVICE='${AFSCP_CALLER_SERVICE:-}' \
    AFSCP_BOOTSTRAP_CALLER_SERVICE='${AFSCP_BOOTSTRAP_CALLER_SERVICE:-}' \
    AFSCP_ORCHESTRATOR_CALLER_SERVICE='${AFSCP_ORCHESTRATOR_CALLER_SERVICE:-}' \
    AFSCP_DEFAULT_VOLUME_ID='${AFSCP_DEFAULT_VOLUME_ID:-}' \
    AFSCP_SERVICE_TOKEN='${AFSCP_SERVICE_TOKEN:-}' \
    AFSCP_BOOTSTRAP_SERVICE_TOKEN='${AFSCP_BOOTSTRAP_SERVICE_TOKEN:-}' \
    KEYCLOAK_CLIENT_ID='${KEYCLOAK_CLIENT_ID}' \
    PUBLIC_KEYCLOAK_BASE_URL='${PUBLIC_KEYCLOAK_BASE_URL}' \
    INTERNAL_KEYCLOAK_BASE_URL='${INTERNAL_KEYCLOAK_BASE_URL}' \
    KEYCLOAK_ISSUER_URL='${KEYCLOAK_ISSUER_URL}' \
    DATABASE_URL='${DATABASE_URL}' \
    REDIS_URL='${REDIS_URL}' \
    MONGO_URL='${MONGO_URL}' \
    MONGO_DB_NAME='${MONGO_DB_NAME}' \
    MINIO_ENDPOINT='${MINIO_ENDPOINT}' \
    MINIO_PORT='${MINIO_PORT}' \
    MINIO_USE_SSL='${MINIO_USE_SSL}' \
    MINIO_ACCESS_KEY='${MINIO_ACCESS_KEY}' \
    MINIO_SECRET_KEY='${MINIO_SECRET_KEY}' \
    MINIO_BUCKET='${MINIO_BUCKET}' \
    FILE_LIBRARY_CLIENT_POSTGRES_HOST='${FILE_LIBRARY_CLIENT_POSTGRES_HOST}' \
    FILE_LIBRARY_CLIENT_POSTGRES_PORT='${FILE_LIBRARY_CLIENT_POSTGRES_PORT}' \
    MBOS_UNIVERSAL_PROXY_BASE_URL='${MBOS_UNIVERSAL_PROXY_BASE_URL}' \
    MBOS_UNIVERSAL_PROXY_ADMIN_TOKEN='${MBOS_UNIVERSAL_PROXY_ADMIN_TOKEN:-}' \
    DEBUG_AGENT_EXECUTION='${DEBUG_AGENT_EXECUTION:-1}' \
    DEBUG_ENDPOINT_PROXY='${DEBUG_ENDPOINT_PROXY:-0}' \
    DEBUG_NOTEBOOK_EXECUTION='${DEBUG_NOTEBOOK_EXECUTION:-0}' && \
  exec npm run api:node:dev
"
wait_http "http://localhost:${PORT_API}/api/v1/openapi.json" "api" 120
capture_listener_pid "${PORT_API}" "${API_PID_FILE}" "api"
printf '%s\n' "${PORT_API}" > "${API_PORT_FILE}"
if [[ -f "${API_PID_FILE}" ]]; then
  local_manual_write_tracked_service_process_state api "$(cat "${API_PID_FILE}")" "start-api" "${PORT_API}" || true
fi
write_ready_file "${API_READY_FILE}"
