#!/usr/bin/env bash
set -euo pipefail

load_agentsmith_presets() {
  local root_dir="$1"
  local preset_file="${root_dir}/infra/deploy/shared/presets/defaults.env"
  [[ -f "${preset_file}" ]] || return 0
  set -a
  # shellcheck disable=SC1090
  source "${preset_file}"
  set +a
  local key preset_key
  for key in \
    SYSTEM_ADMIN_USERNAME \
    SYSTEM_ADMIN_PASSWORD \
    INTEGRATION_DEV_ADMIN_USERNAME \
    INTEGRATION_DEV_ADMIN_PASSWORD \
    INTEGRATION_USER_USERNAME \
    INTEGRATION_USER_PASSWORD \
    INTEGRATION_MEMBER_USERNAME \
    INTEGRATION_MEMBER_PASSWORD \
    MBOS_DEFAULT_WORKSPACE_ID \
    MBOS_DEFAULT_WORKSPACE_NAME \
    MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL \
    MBOS_DEMO_PROJECT_NAME \
    MBOS_DEMO_CREDENTIAL_NAME \
    MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME \
    MBOS_DEMO_OPENAI_ENDPOINT_NAME \
    MBOS_DEMO_EXTERNAL_AGENT_NAME \
    MBOS_DEMO_INTERNAL_AGENT_NAME \
    DEMO_ENDPOINT_API_KEY \
    DEMO_ENDPOINT_BASE_URL \
    DEMO_ENDPOINT_PROTOCOL \
    DEMO_ENDPOINT_MODEL \
    DEMO_ENDPOINT_MAX_CONTEXT_TOKENS \
    DEMO_ENDPOINT_MAX_OUTPUT_TOKENS
  do
    preset_key="AGENTSMITH_PRESET_${key}"
    if [[ -n "${!key:-}" ]]; then
      printf -v "${preset_key}" '%s' "${!key}"
      export "${preset_key}"
    fi
  done
}

apply_non_environment_preset_defaults() {
  local key
  for key in \
    SYSTEM_ADMIN_USERNAME \
    SYSTEM_ADMIN_PASSWORD \
    INTEGRATION_DEV_ADMIN_USERNAME \
    INTEGRATION_DEV_ADMIN_PASSWORD \
    INTEGRATION_USER_USERNAME \
    INTEGRATION_USER_PASSWORD \
    INTEGRATION_MEMBER_USERNAME \
    INTEGRATION_MEMBER_PASSWORD \
    MBOS_DEFAULT_WORKSPACE_ID \
    MBOS_DEFAULT_WORKSPACE_NAME \
    MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL \
    MBOS_DEMO_PROJECT_NAME \
    MBOS_DEMO_CREDENTIAL_NAME \
    MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME \
    MBOS_DEMO_OPENAI_ENDPOINT_NAME \
    MBOS_DEMO_EXTERNAL_AGENT_NAME \
    MBOS_DEMO_INTERNAL_AGENT_NAME
  do
    local preset_key="AGENTSMITH_PRESET_${key}"
    if [[ -n "${!preset_key:-}" ]]; then
      printf -v "${key}" '%s' "${!preset_key}"
      export "${key}"
    fi
  done
}

apply_demo_endpoint_defaults() {
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_API_KEY:-}" ]]; then
    DEMO_ENDPOINT_API_KEY="${AGENTSMITH_PRESET_DEMO_ENDPOINT_API_KEY}"
  fi
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_BASE_URL:-}" ]]; then
    DEMO_ENDPOINT_BASE_URL="${AGENTSMITH_PRESET_DEMO_ENDPOINT_BASE_URL}"
  fi
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_PROTOCOL:-}" ]]; then
    DEMO_ENDPOINT_PROTOCOL="${AGENTSMITH_PRESET_DEMO_ENDPOINT_PROTOCOL}"
  fi
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_MODEL:-}" ]]; then
    DEMO_ENDPOINT_MODEL="${AGENTSMITH_PRESET_DEMO_ENDPOINT_MODEL}"
  fi
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_MAX_CONTEXT_TOKENS:-}" ]]; then
    DEMO_ENDPOINT_MAX_CONTEXT_TOKENS="${AGENTSMITH_PRESET_DEMO_ENDPOINT_MAX_CONTEXT_TOKENS}"
  fi
  if [[ -n "${AGENTSMITH_PRESET_DEMO_ENDPOINT_MAX_OUTPUT_TOKENS:-}" ]]; then
    DEMO_ENDPOINT_MAX_OUTPUT_TOKENS="${AGENTSMITH_PRESET_DEMO_ENDPOINT_MAX_OUTPUT_TOKENS}"
  fi
  if [[ -n "${DEMO_ENDPOINT_API_KEY:-}" ]]; then
    DEPLOY_ENDPOINT_API_KEY="${DEMO_ENDPOINT_API_KEY}"
  fi
  if [[ -n "${DEMO_ENDPOINT_PROTOCOL:-}" ]]; then
    DEPLOY_ENDPOINT_PROTOCOL="${DEMO_ENDPOINT_PROTOCOL}"
  fi
  if [[ -n "${DEMO_ENDPOINT_BASE_URL:-}" ]]; then
    case "${DEMO_ENDPOINT_PROTOCOL:-openai_compatible}" in
      anthropic_compatible)
        DEPLOY_ANTHROPIC_BASE_URL="${DEMO_ENDPOINT_BASE_URL}"
        ;;
      *)
        DEPLOY_OPENAI_BASE_URL="${DEMO_ENDPOINT_BASE_URL}"
        ;;
    esac
  fi
  if [[ -n "${DEMO_ENDPOINT_MODEL:-}" ]]; then
    DEPLOY_ENDPOINT_MODEL="${DEMO_ENDPOINT_MODEL}"
  fi
  if [[ -n "${DEMO_ENDPOINT_MAX_CONTEXT_TOKENS:-}" ]]; then
    MBOS_DEMO_MODEL_CONTEXT_TOKENS="${DEMO_ENDPOINT_MAX_CONTEXT_TOKENS}"
  fi
  if [[ -n "${DEMO_ENDPOINT_MAX_OUTPUT_TOKENS:-}" ]]; then
    MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS="${DEMO_ENDPOINT_MAX_OUTPUT_TOKENS}"
  fi
  export \
    DEPLOY_ENDPOINT_API_KEY \
    DEPLOY_ENDPOINT_PROTOCOL \
    DEPLOY_ANTHROPIC_BASE_URL \
    DEPLOY_OPENAI_BASE_URL \
    DEPLOY_ENDPOINT_MODEL \
    DEMO_ENDPOINT_PROTOCOL \
    MBOS_DEMO_MODEL_CONTEXT_TOKENS \
    MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS
}
