function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlNumber(value: number): string {
  if (!Number.isFinite(value) || value <= 0) {
    throw new Error(`invalid_codex_numeric_config:${value}`);
  }
  return String(Math.floor(value));
}

export function buildTaskCodexConfig(args: {
  model: string;
  endpointProxyBase: string;
  wireApi: 'responses' | 'chat';
  modelContextWindow?: number;
  modelAutoCompactTokenLimit?: number;
  modelCatalogPath?: string;
  proxyAuthHeaderEnvName?: string;
}): string {
  const lines: string[] = [
    '# Generated by @mbos/notebook-codex-runner for this task workspace.',
    '# Task-scoped Codex config loaded from ~/.codex/config.toml',
    `model = ${tomlString(args.model)}`,
    'model_provider = "proxy"',
    '',
    '# Reduce unsupported built-in tool usage for OpenAI-compatible third-party providers.',
    'web_search = "disabled"',
    '# Keep notebook output compact; reasoning is still available in tool/provider responses when needed.',
    'hide_agent_reasoning = true',
  ];
  if (typeof args.modelContextWindow === 'number') {
    lines.push(`model_context_window = ${tomlNumber(args.modelContextWindow)}`);
  }
  if (typeof args.modelAutoCompactTokenLimit === 'number') {
    lines.push(`model_auto_compact_token_limit = ${tomlNumber(args.modelAutoCompactTokenLimit)}`);
  }
  if (args.modelCatalogPath && args.modelCatalogPath.trim().length > 0) {
    lines.push(`model_catalog_json = ${tomlString(args.modelCatalogPath)}`);
  }
  lines.push('');
  lines.push('[model_providers.proxy]');
  lines.push(`name = ${tomlString('Proxy')}`);
  lines.push(`base_url = ${tomlString(args.endpointProxyBase)}`);
  lines.push(`wire_api = ${tomlString(args.wireApi)}`);
  if (args.proxyAuthHeaderEnvName && args.proxyAuthHeaderEnvName.trim().length > 0) {
    lines.push(`env_http_headers = { Authorization = ${tomlString(args.proxyAuthHeaderEnvName)} }`);
  }
  return `${lines.join('\n')}\n`;
}

export function buildCodexExecArgs(args: {
  model: string;
  prompt: string;
  cwd: string;
  endpointProxyBase: string;
  wireApi: 'responses' | 'chat';
  modelContextWindow?: number;
  modelAutoCompactTokenLimit?: number;
  modelCatalogPath?: string;
  resumeSession?: boolean;
}): string[] {
  const cliArgs = [
    'exec',
    '--skip-git-repo-check',
    '--json',
    '--model',
    args.model,
    '-c',
    'model_provider="proxy"',
    '-c',
    'model_providers.proxy.name="Proxy"',
    '-c',
    `model_providers.proxy.base_url=${JSON.stringify(args.endpointProxyBase)}`,
    '-c',
    `model_providers.proxy.wire_api=${JSON.stringify(args.wireApi)}`,
    '-c',
    'project_root_markers=[]',
    '-c',
    `projects.${JSON.stringify(args.cwd)}.trust_level="trusted"`,
    '-c',
    'web_search="disabled"',
    '-c',
    'hide_agent_reasoning=true',
  ];
  if (typeof args.modelContextWindow === 'number') {
    cliArgs.push(
      '-c',
      `model_context_window=${tomlNumber(args.modelContextWindow)}`,
    );
  }
  if (typeof args.modelAutoCompactTokenLimit === 'number') {
    cliArgs.push(
      '-c',
      `model_auto_compact_token_limit=${tomlNumber(args.modelAutoCompactTokenLimit)}`,
    );
  }
  if (args.modelCatalogPath && args.modelCatalogPath.trim().length > 0) {
    cliArgs.push(
      '-c',
      `model_catalog_json=${JSON.stringify(args.modelCatalogPath)}`,
    );
  }
  cliArgs.splice(1, 0, '--dangerously-bypass-approvals-and-sandbox');
  if (args.resumeSession) {
    cliArgs.splice(1, 0, 'resume', '--last');
  }
  cliArgs.push(args.prompt);
  return cliArgs;
}

export function buildTaskCodexModelCatalog(args: {
  model: string;
  modelContextWindow: number;
  modelAutoCompactTokenLimit: number;
  inputModalities?: string[];
  supportsSearchTool?: boolean;
  supportsParallelToolCalls?: boolean;
}): string {
  const inputModalities = Array.isArray(args.inputModalities) && args.inputModalities.length > 0
    ? [...new Set(args.inputModalities.map((item) => item.trim()).filter((item) => item.length > 0))]
    : ['text'];
  const catalog = {
    models: [
      {
        slug: args.model,
        display_name: args.model,
        description: 'AgentSmith endpoint-backed Codex model.',
        default_reasoning_level: 'medium',
        supported_reasoning_levels: [
          { effort: 'low', description: 'Fast responses with lighter reasoning' },
          { effort: 'medium', description: 'Balances speed and reasoning depth for everyday tasks' },
          { effort: 'high', description: 'Greater reasoning depth for complex problems' },
          { effort: 'xhigh', description: 'Extra high reasoning depth for complex problems' },
        ],
        shell_type: 'shell_command',
        visibility: 'list',
        supported_in_api: true,
        priority: 0,
        availability_nux: null,
        upgrade: null,
        base_instructions:
          'You are Codex, a coding agent based on GPT-5. You and the user share the same workspace and collaborate to achieve the user\'s goals.',
        model_messages: null,
        supports_reasoning_summaries: false,
        default_reasoning_summary: 'auto',
        support_verbosity: false,
        default_verbosity: null,
        apply_patch_tool_type: 'freeform',
        web_search_tool_type: 'text',
        truncation_policy: { mode: 'bytes', limit: 10000 },
        supports_parallel_tool_calls: args.supportsParallelToolCalls ?? false,
        supports_image_detail_original: false,
        context_window: Math.floor(args.modelContextWindow),
        auto_compact_token_limit: Math.floor(args.modelAutoCompactTokenLimit),
        effective_context_window_percent: 90,
        experimental_supported_tools: [],
        input_modalities: inputModalities,
        supports_search_tool: args.supportsSearchTool ?? false,
      },
    ],
  };
  return `${JSON.stringify(catalog, null, 2)}\n`;
}
