import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { TaskWorkspacePaths } from './task-workspace.js';

export type NotebookTaskInput = {
  kind?: 'library_object' | 'artifact' | 'url';
  library_id?: string;
  key?: string;
  task_id?: string;
  artifact_id?: string;
  task_relative_path?: string;
  url?: string;
  imported_library_id?: string;
  imported_key?: string;
  filename?: string;
  file_type?: string;
  file_size?: number;
};

export type NotebookExecutionContext = {
  task_id?: string;
  run_id?: string;
  workspace_binding_mode?: 'file_library' | 'pre_mounted';
};

type NotebookAssetDebugLog = (message: string, extra?: Record<string, unknown>) => void;

export function buildNotebookHeadlessPreamble(args: {
  artifactsDir: string;
}): string {
  return [
    'Notebook execution policy (headless execution):',
    '- This environment is headless. Do not open GUI windows or interactive viewers.',
    '- Do not call blocking UI display operations such as matplotlib plt.show().',
    `- Save charts/images/files to the artifacts directory: ${args.artifactsDir}`,
    '- Put final textual conclusions in your response; put generated files in artifacts.',
    '',
    'Use files already present in the workspace to complete the user request and mention generated artifact filenames in your final response.',
    '',
  ].join('\n');
}

function buildNotebookAgentsMd(): string {
  return [
    '# AGENTS.md (generated by @mbos/notebook-codex-runner)',
    '',
    '## Notebook Execution Rules (Mandatory)',
    '',
    '1. This task runs in a headless environment. Do not open GUI windows or interactive viewers.',
    '2. Do not call blocking display APIs (for example: matplotlib.pyplot.show()).',
    '3. Save generated files/charts/images into `./.artifacts/`.',
    '4. Put final conclusions in the response message, and mention generated artifact filenames.',
    '5. The current working directory is the user file workspace root for this task.',
    '6. `HOME` is a runner-private runtime home outside `cwd`. Keep dynamic config, caches, installs, toolchains, and auth material under `HOME`.',
    '7. Builtin skills are installed under `~/.agents/skills` in the runtime home. Do not rely on `/etc/codex` for mutable runtime state.',
    '8. Builtin skills may declare machine-readable capability contracts for context and credential access. Prefer those capability-aware builtin skills before browsing workspace files for hidden config.',
    '9. Use the `mbos-context` builtin skill when you need manual edits of member/task context, inspect project_member context, simple credentials, or shared guidance.',
    '10. Managed OAuth credentials such as Feishu stay in AgentSmith-managed connections and are exposed through read-only context capability views like `managed_credentials.feishu`.',
    '11. If you need Python / Node / Rust tools or libraries, install them in user mode only so they stay inside the runtime home.',
    '12. Never write dynamic config, package installs, caches, or auth material into the user file workspace root; generated deliverables belong in `./.artifacts/`.',
    '',
    '## Output Convention',
    '',
    '- Text summary -> final response message',
    '- Files/images -> `./.artifacts/` (system will collect these as notebook artifacts)',
    '- AgentSmith runner state -> `$HOME/.mbos/`',
    '- Codex runtime state -> `$HOME/.codex/`',
    '- Builtin + user skills -> `$HOME/.agents/skills/`',
    '- Agent-facing persistent context -> use capability-aware builtin skills first; use `mbos-context` to write member/task context and inspect project_member/shared context',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: use user installs rooted at `~/.local` (for example `python3 -m pip install --user ...`).',
    '- Node: use a user prefix rooted at `~/.local` and avoid global/system installs.',
    '- Rust: use `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup` inside the runtime home.',
    '- Prefer commands that keep binaries under `~/.local/bin` or `~/.cargo/bin`.',
    '',
  ].join('\n');
}

function buildRunnerRuntimeMd(): string {
  return [
    '# RUNNER_RUNTIME.md (generated by @mbos/notebook-codex-runner)',
    '',
    '## Runtime Contract',
    '',
    '- `cwd` is the user file workspace root.',
    '- `HOME` is the runner-private runtime home and is intentionally separate from `cwd`.',
    '- All dynamic configuration, caches, package installs, toolchains, and mutable auth material must stay under the runner-private runtime home.',
    '- Builtin skills are installed under `~/.agents/skills`.',
    '- Agent-facing member/task/project_member/project/workspace context is provided through AgentSmith Context Store APIs, capability-aware builtin skill contracts, and the `mbos-context` generic skill.',
    '- `member` means current-workspace member-private context; `task` means context owned by the current member task; `project_member` means current-project member-private context; `project/workspace` are shared contexts.',
    '- Agent execution may write member/task context, read project_member context, and read project/workspace context; project_member/project/workspace remain read-only to agent tickets.',
    '- Managed OAuth credentials are exposed as read-only context capability views such as `managed_credentials.feishu`.',
    '- Builtin skills can ship machine-readable capability contracts so deterministic helpers can resolve required context or credentials without hard-coding another skill name.',
    '- Codex runtime state is stored under `$HOME/.codex`.',
    '- Notebook output files belong in `cwd/.artifacts`.',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: install with user mode rooted at `~/.local`.',
    '- Node: install with a user prefix rooted at `~/.local`.',
    '- Rust: keep `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup`.',
    '- Never write mutable runtime state to `/etc`, `/usr/local`, `/opt`, or shared system directories.',
    '',
  ].join('\n');
}

export async function prepareNotebookWorkspaceAssets(args: {
  cwd: string;
  paths: TaskWorkspacePaths;
  executionContext: NotebookExecutionContext;
  taskInputs: NotebookTaskInput[];
  debugLog?: NotebookAssetDebugLog;
}): Promise<{
  artifactsDir: string;
}> {
  const { cwd, paths, executionContext, taskInputs, debugLog } = args;
  const artifactsDir = paths.artifactsDir;
  await withFsOpTimeout(
    'notebook_assets_mkdir_mbos',
    mkdir(paths.mbosDir, { recursive: true }),
    debugLog,
    { cwd, target: paths.mbosDir },
  );
  await withFsOpTimeout(
    'notebook_assets_mkdir_artifacts',
    mkdir(artifactsDir, { recursive: true }),
    debugLog,
    { cwd, target: artifactsDir },
  );
  debugLog?.('notebook_assets_inputs_ignored', {
    cwd,
    task_inputs_count: taskInputs.length,
  });
  const agentsPath = join(cwd, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    await withFsOpTimeout(
      'notebook_assets_write_agents_md',
      writeFile(agentsPath, buildNotebookAgentsMd(), 'utf-8'),
      debugLog,
      { cwd, target: agentsPath, workspace_binding_mode: executionContext.workspace_binding_mode ?? null },
    );
  }
  const runtimeContractPath = join(paths.mbosDir, 'RUNNER_RUNTIME.md');
  await withFsOpTimeout(
    'notebook_assets_write_runner_runtime_md',
    writeFile(runtimeContractPath, buildRunnerRuntimeMd(), 'utf-8'),
    debugLog,
    { cwd, target: runtimeContractPath },
  );
  return { artifactsDir };
}

async function withFsOpTimeout<T>(
  name: string,
  promise: Promise<T>,
  debugLog?: NotebookAssetDebugLog,
  extra?: Record<string, unknown>,
): Promise<T> {
  const timeoutMs = Number.parseInt(process.env.MBOS_NOTEBOOK_ASSET_IO_TIMEOUT_MS ?? '30000', 10);
  const startedAt = Date.now();
  debugLog?.(`${name}_start`, extra);
  let timer: NodeJS.Timeout | undefined;
  try {
    const result = await Promise.race<T>([
      promise,
      new Promise<T>((_resolve, reject) => {
        timer = setTimeout(() => {
          reject(new Error(`${name}_timeout_after_${String(timeoutMs)}ms`));
        }, timeoutMs);
      }),
    ]);
    debugLog?.(`${name}_done`, {
      ...extra,
      duration_ms: Date.now() - startedAt,
    });
    return result;
  } finally {
    if (timer) clearTimeout(timer);
  }
}
