#!/usr/bin/env bash
set -euo pipefail

unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY
unset no_proxy NO_PROXY

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SANDBOX_ROOT="$(cd "${ROOT_DIR}/../mbos-sandbox-v1" && pwd)"
KIND_CONFIG_PATH="${ROOT_DIR}/infra/deploy/demo/kind/config.yaml"
# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/lib/backend-real-state.sh"
source "${ROOT_DIR}/scripts/lib/k8s-external-services.sh"
source "${ROOT_DIR}/scripts/lib/backend-real-env.sh"
source "${ROOT_DIR}/scripts/lib/internal-backend-real-gate.sh"
source "${ROOT_DIR}/scripts/lib/runner-image-common.sh"
source "${ROOT_DIR}/scripts/lib/runtime-verification.sh"
source "${ROOT_DIR}/scripts/lib/backend-real-gate-ports.sh"
# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/scenarios/common.sh"

info() { echo "[internal-chat-real-gate] $*"; }
die() { echo "[internal-chat-real-gate] $*" >&2; exit 1; }

ORIGINAL_INTEGRATION_API_PORT="${INTEGRATION_API_PORT:-}"
ORIGINAL_INTEGRATION_WEB_PORT="${INTEGRATION_WEB_PORT:-}"
load_backend_real_env
if [[ -n "${ORIGINAL_INTEGRATION_API_PORT}" ]]; then
  export INTEGRATION_API_PORT="${ORIGINAL_INTEGRATION_API_PORT}"
fi
if [[ -n "${ORIGINAL_INTEGRATION_WEB_PORT}" ]]; then
  export INTEGRATION_WEB_PORT="${ORIGINAL_INTEGRATION_WEB_PORT}"
fi
export_backend_real_endpoint_env

[[ -n "${BACKEND_REAL_API_KEY_VALUE:-}" ]] || die "missing PRESET_ENDPOINT_API_KEY in .env.backend-real"

API_PORT="${INTEGRATION_API_PORT:-20064}"
WEB_PORT="${INTEGRATION_WEB_PORT:-3065}"
INTEGRATION_POSTGRES_PORT="${INTEGRATION_POSTGRES_PORT:-25432}"
INTEGRATION_MONGO_PORT="${INTEGRATION_MONGO_PORT:-27027}"
INTEGRATION_REDIS_PORT="${INTEGRATION_REDIS_PORT:-26379}"
INTEGRATION_MINIO_API_PORT="${INTEGRATION_MINIO_API_PORT:-29000}"
INTEGRATION_MINIO_CONSOLE_PORT="${INTEGRATION_MINIO_CONSOLE_PORT:-29001}"
INTEGRATION_KEYCLOAK_PORT="${INTEGRATION_KEYCLOAK_PORT:-28081}"
SANDBOX_PORT="${INTERNAL_SANDBOX_MANAGER_PORT:-28080}"
SANDBOX_SERVICE_KEY_VALUE="${SANDBOX_SERVICE_KEY:-agentsmith-internal-test-key}"
K8S_NAMESPACE="${INTERNAL_AGENT_K8S_NAMESPACE:-agentsmith-sandbox}"
CSI_DRIVER="${INTERNAL_AGENT_JUICEFS_CSI_DRIVER:-csi.juicefs.com}"
RUNNER_KIND="${INTEGRATION_INTERNAL_AGENT_RUNNER_KIND:-chat}"
RUNNER_IMAGE="${INTEGRATION_INTERNAL_CHAT_AGENT_IMAGE:-${INTEGRATION_INTERNAL_AGENT_IMAGE:-$(runner_default_image "${RUNNER_KIND}")}}"
RUNNER_BASE_IMAGE="${INTEGRATION_CHAT_RUNNER_BASE_DOCKER_IMAGE:-${INTEGRATION_INTERNAL_AGENT_BASE_IMAGE:-$(runner_default_base_image "${RUNNER_KIND}")}}"
BUILD_RUNNER_IMAGE="${INTEGRATION_BUILD_INTERNAL_AGENT_IMAGE:-1}"
DOCKER_BUILD_PROXY_VALUE="${INTEGRATION_DOCKER_BUILD_PROXY:-${DOCKER_BUILD_PROXY:-}}"
WORKSPACE_CAPACITY="${INTERNAL_AGENT_WORKSPACE_CAPACITY:-1Pi}"
STORAGE_CLASS_NAME="${INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME:-}"
MOUNT_OPTIONS="${INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS:-}"
SUBDIR="${INTERNAL_AGENT_JUICEFS_SUBDIR:-}"
MOUNT_SERVICE_ACCOUNT="${INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT:-}"
MOUNT_IMAGE_OVERRIDE="${INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE:-}"
JUICEFS_MOUNT_IMAGE="${INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE:-juicedata/mount:ce-v1.3.1}"
JUICEFS_CSI_VERSION="${JUICEFS_CSI_VERSION:-v0.31.3}"
JUICEFS_CSI_MANIFEST_PATH="${JUICEFS_CSI_MANIFEST_PATH:-${ROOT_DIR}/infra/deploy/cluster/addons/juicefs-csi/upstream-manifest.yaml}"
JUICEFS_CSI_NAMESPACE="${JUICEFS_CSI_NAMESPACE:-kube-system}"
ensure_backend_real_state
INTERNAL_REAL_DIR="${INTERNAL_REAL_DIR:-$(backend_real_tmp_file internal-chat)}"
mkdir -p "${INTERNAL_REAL_DIR}"
INTERNAL_REAL_DIR="$(realpath -m "${INTERNAL_REAL_DIR}")"
export RUNTIME_LINE_ID="${RUNTIME_LINE_ID:-$(basename "${INTERNAL_REAL_DIR}")}"
export RUNTIME_RUNNER_MODES="${RUNTIME_RUNNER_MODES:-external_host,internal_k8s}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:-mbos}"
KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID:-agentsmith}"
clear_runtime_stack_env
resolve_loopback_runtime_stack "${API_PORT}" "${WEB_PORT}" "${INTEGRATION_KEYCLOAK_PORT}" "${KEYCLOAK_REALM}" "${KEYCLOAK_CLIENT_ID}"
gate_evidence_init "${INTERNAL_REAL_DIR}" "internal_chat_backend_real"
gate_write_runtime_descriptor "${INTERNAL_REAL_DIR}" "internal_chat_backend_real"
gate_write_resolved_env "${INTERNAL_REAL_DIR}"
SANDBOX_LOG="${INTERNAL_SANDBOX_MANAGER_LOG:-${INTERNAL_REAL_DIR}/sandbox-manager.log}"
CONFIG_PATH="${INTERNAL_SANDBOX_MANAGER_CONFIG:-${INTERNAL_REAL_DIR}/sandbox-manager.yaml}"
CONFIG_PATH="$(realpath -m "${CONFIG_PATH}")"
CONTROL_SCRIPT="${ROOT_DIR}/scripts/lib/internal-sandbox-real-control.sh"
STATE_FILE="${INTERNAL_REAL_DIR}/sandbox-control.env"
CLEANER_LOG="${INTERNAL_SANDBOX_CLEANER_LOG:-${INTERNAL_REAL_DIR}/sandbox-cleaner.log}"
CLEANER_LOG="$(realpath -m "${CLEANER_LOG}")"
SANDBOX_LOG="$(realpath -m "${SANDBOX_LOG}")"
mkdir -p "$(dirname "${CONFIG_PATH}")" "$(dirname "${CLEANER_LOG}")" "$(dirname "${SANDBOX_LOG}")"
CLEANER_INTERVAL_SECONDS="${INTERNAL_SANDBOX_CLEANER_INTERVAL_SECONDS:-15}"
KEEP_FAILED_ENV="${INTERNAL_REAL_KEEP_FAILED_ENV:-0}"
GATE_STATUS=0
CURRENT_SANDBOX_STATE_FILE=""
CONTEXT_NAME="$(kubectl config current-context 2>/dev/null || true)"
DEFAULT_KIND_CLUSTER_NAME="agentsmith"
if [[ -z "${INTERNAL_AGENT_KIND_CLUSTER_NAME:-}" ]] && kind get clusters 2>/dev/null | grep -qx 'mbos'; then
  DEFAULT_KIND_CLUSTER_NAME="mbos"
fi
KIND_CLUSTER_NAME="${INTERNAL_AGENT_KIND_CLUSTER_NAME:-${DEFAULT_KIND_CLUSTER_NAME}}"
KIND_CONTEXT_NAME="kind-${KIND_CLUSTER_NAME}"
MONGO_URL="${MONGO_URL:-mongodb://mbos:mbos_dev_password@localhost:${INTEGRATION_MONGO_PORT}/admin}"
MONGO_DB_NAME="${MONGO_DB_NAME:-mbos}"
SPEC_PATH="e2e/integration-internal-chat-runner.spec.ts"
SPEC_SLUG="$(basename "${SPEC_PATH}" .spec.ts)"

cleanup() {
  if [[ "${KEEP_FAILED_ENV}" == "1" && "${GATE_STATUS}" -ne 0 ]]; then
    info "keeping failed sandbox manager environment for inspection"
    if [[ -n "${CURRENT_SANDBOX_STATE_FILE}" && -f "${CURRENT_SANDBOX_STATE_FILE}" ]]; then
      # shellcheck disable=SC1090
      source "${CURRENT_SANDBOX_STATE_FILE}"
      info "sandbox_log=${SANDBOX_LOG}"
      info "cleaner_log=${CLEANER_LOG}"
      info "state_file=${CURRENT_SANDBOX_STATE_FILE}"
    else
      info "sandbox_log=${SANDBOX_LOG}"
      info "cleaner_log=${CLEANER_LOG}"
      info "state_file=${STATE_FILE}"
    fi
    return 0
  fi
  if [[ -n "${CURRENT_SANDBOX_STATE_FILE}" ]]; then
    INTERNAL_SANDBOX_REAL_STATE_FILE="${CURRENT_SANDBOX_STATE_FILE}" bash "${CONTROL_SCRIPT}" stop-cleaner >/dev/null 2>&1 || true
    INTERNAL_SANDBOX_REAL_STATE_FILE="${CURRENT_SANDBOX_STATE_FILE}" bash "${CONTROL_SCRIPT}" stop-manager >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

info "running internal chat backend-real integration"
cleanup_gate_ports "${API_PORT}" "${WEB_PORT}" "${SPEC_PATH}"
prepare_internal_backend_real_gate_runtime

SPEC_STATE_FILE="$(prepare_internal_backend_real_spec_runtime "${SPEC_SLUG}" "with-cleaner")"
set +e
(
  cd "${ROOT_DIR}" && \
    BACKEND_REAL_API_KEY="${BACKEND_REAL_API_KEY_VALUE}" \
    SANDBOX_MANAGER_URL="${SANDBOX_MANAGER_URL_VALUE}" \
    SANDBOX_SERVICE_KEY="${SANDBOX_SERVICE_KEY_VALUE}" \
    DATABASE_URL="postgresql://mbos:mbos_dev_password@127.0.0.1:${INTEGRATION_POSTGRES_PORT}/mbos" \
    MONGO_URL="${MONGO_URL}" \
    MONGO_DB_NAME="${MONGO_DB_NAME}" \
    REDIS_URL="redis://127.0.0.1:${INTEGRATION_REDIS_PORT}" \
    MINIO_ENDPOINT="127.0.0.1" \
    MINIO_PORT="${INTEGRATION_MINIO_API_PORT}" \
    KEYCLOAK_BASE_URL="${KEYCLOAK_BASE_URL}" \
    KEYCLOAK_URL="${KEYCLOAK_BASE_URL%/}/realms" \
    INTERNAL_AGENT_K8S_NAMESPACE="${K8S_NAMESPACE}" \
    INTERNAL_AGENT_JUICEFS_CSI_DRIVER="${CSI_DRIVER}" \
    INTERNAL_AGENT_WORKSPACE_CAPACITY="${WORKSPACE_CAPACITY}" \
    INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME="${STORAGE_CLASS_NAME}" \
    INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS="${MOUNT_OPTIONS}" \
    INTERNAL_AGENT_JUICEFS_SUBDIR="${SUBDIR}" \
    INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT="${MOUNT_SERVICE_ACCOUNT}" \
    INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE="${MOUNT_IMAGE_OVERRIDE}" \
    INTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE="${INTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE_VALUE}" \
    INTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE="${INTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE_VALUE}" \
    JUICEFS_BUCKET_ENDPOINT_FOR_INTERNAL_MOUNT="${JUICEFS_BUCKET_ENDPOINT_FOR_INTERNAL_MOUNT_VALUE}" \
    INTEGRATION_CLIENT_JUICEFS_META_HOST_OVERRIDE="${INTEGRATION_CLIENT_JUICEFS_META_HOST_OVERRIDE_VALUE}" \
    INTEGRATION_CLIENT_JUICEFS_META_PORT_OVERRIDE="${INTEGRATION_CLIENT_JUICEFS_META_PORT_OVERRIDE_VALUE}" \
    INTEGRATION_CLIENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE="${INTEGRATION_CLIENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE_VALUE}" \
    INTEGRATION_INTERNAL_AGENT_IMAGE="${RUNNER_IMAGE}" \
    INTEGRATION_INTERNAL_CHAT_AGENT_IMAGE="${RUNNER_IMAGE}" \
    INTEGRATION_CHAT_RUNNER_BASE_DOCKER_IMAGE="${RUNNER_BASE_IMAGE}" \
    INTEGRATION_CHAT_RUNNER_REBUILD_BASE_IMAGE=0 \
    INTEGRATION_CHAT_RUNNER_REBUILD_IMAGE=0 \
    AGENT_EXECUTION_WS_BASE_URL="ws://${KIND_GATEWAY}:${API_PORT}" \
    INTERNAL_SANDBOX_REAL_STATE_FILE="${SPEC_STATE_FILE}" \
    INTEGRATION_KEEP_FAILED_ENV="${KEEP_FAILED_ENV}" \
    POSTGRES_PORT="${INTEGRATION_POSTGRES_PORT}" \
    MONGO_PORT="${INTEGRATION_MONGO_PORT}" \
    REDIS_PORT="${INTEGRATION_REDIS_PORT}" \
    MINIO_API_PORT="${INTEGRATION_MINIO_API_PORT}" \
    MINIO_CONSOLE_PORT="${INTEGRATION_MINIO_CONSOLE_PORT}" \
    KEYCLOAK_PORT="${INTEGRATION_KEYCLOAK_PORT}" \
    INTEGRATION_API_PORT="${API_PORT}" \
    INTEGRATION_WEB_PORT="${WEB_PORT}" \
    INTEGRATION_API_BASE="http://127.0.0.1:${API_PORT}" \
    INTEGRATION_BASE_URL="http://localhost:${WEB_PORT}" \
    INTEGRATION_LOG_DIR="${INTERNAL_REAL_DIR}/${SPEC_SLUG}" \
    bash scripts/run-integration-e2e-full.sh "${SPEC_PATH}"
)
GATE_STATUS=$?
set -e

if [[ "${GATE_STATUS}" -ne 0 ]]; then
  exit "${GATE_STATUS}"
fi

info "internal chat backend-real gate passed"
gate_record_success "${INTERNAL_REAL_DIR}" "internal_chat_spec"
