import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

describe('user story contract docs', () => {
  it('documents the current runtimeData and step note schema from story-contract', async () => {
    const docSource = await readFile(path.resolve('docs/contracts/user-story-contract-v1.md'), 'utf-8');
    const contractSource = await readFile(path.resolve('e2e/story-contract.ts'), 'utf-8');

    expect(contractSource).toContain('note?: string;');
    expect(contractSource).toContain('runtimeData?: StoryRuntimeData;');
    expect(contractSource).toContain('export type StoryRuntimeAgentTaskTurnDefinition');
    expect(contractSource).toContain('export type StoryRuntimeAgentTaskFlowDefinition');
    expect(contractSource).toContain('export type StoryRuntimeVisualReviewSceneDefinition');
    expect(contractSource).toContain('export type StoryRuntimeVisualReviewDefinition');
    expect(contractSource).toContain('export type StoryRuntimeVisualReviewAgentTaskDefinition');
    expect(contractSource).toContain('export type StoryRuntimeVisualSemanticAssertionsDefinition');
    expect(contractSource).toContain('export type StoryRuntimeData');
    expect(contractSource).toContain('export type StoryVisualReviewScenarioGroup');
    expect(contractSource).toContain('export type StoryVisualReviewCaptureMode');
    expect(contractSource).toContain('export type StoryVisualReviewTheme');
    expect(contractSource).toContain('export type StoryVisualReviewViewport');
    expect(contractSource).toContain('export type StoryKind');
    expect(contractSource).toContain('export type StoryGatePolicy');
    expect(contractSource).toContain('export type StoryExternalDependency');
    expect(contractSource).toContain('family: string;');
    expect(contractSource).toContain('personas: readonly string[];');
    expect(contractSource).toContain('kind: StoryKind;');
    expect(contractSource).toContain('gatePolicy: StoryGatePolicy;');
    expect(contractSource).toContain('externalDependencies: readonly StoryExternalDependency[];');

    expect(docSource).toContain('- `runtimeData?: StoryRuntimeData`');
    expect(docSource).toContain('- `note?: string`');
    expect(docSource).toContain('- `family: string`');
    expect(docSource).toContain('- `personas: string[]`');
    expect(docSource).toContain('- `kind: StoryKind`');
    expect(docSource).toContain('- `gatePolicy: StoryGatePolicy`');
    expect(docSource).toContain('- `externalDependencies: StoryExternalDependency[]`');
    expect(docSource).toContain('### Story pyramid metadata');
    expect(docSource).toContain('### Gate policy');
    expect(docSource).toContain('### External dependency');
    expect(docSource).toContain('- `tier:');
    expect(docSource).toContain('- `requiredEvidence:');
    expect(docSource).toContain('- `dependencyId: string`');
    expect(docSource).toContain('- `kind:');
    expect(docSource).toContain('- `required?: boolean`');
    expect(docSource).toContain('### Runtime data');
    expect(docSource).toContain('- `agentTask?: Record<string, StoryRuntimeAgentTaskFlowDefinition>`');
    expect(docSource).toContain('- `visualReview?: StoryRuntimeVisualReviewDefinition`');
    expect(docSource).toContain('### Visual review scene');
    expect(docSource).toContain('- `sceneId: string`');
    expect(docSource).toContain('- `scenarioId: string`');
    expect(docSource).toContain('- `scenario: string`');
    expect(docSource).toContain('- `group: StoryVisualReviewScenarioGroup`');
    expect(docSource).toContain('- `codeRefs: string[]`');
    expect(docSource).toContain('- `capture: StoryVisualReviewCaptureMode`');
    expect(docSource).toContain('- `authLane?: StoryAuthLane`');
    expect(docSource).toContain('- `screenshotBaseName?: string`');
    expect(docSource).toContain('- `themes?: StoryVisualReviewTheme[]`');
    expect(docSource).toContain('`default` for a single canonical screenshot');
    expect(docSource).toContain('- `viewport?: StoryVisualReviewViewport`');
    expect(docSource).toContain('- `setupNotes?: string[]`');
    expect(docSource).toContain('- `semanticAssertions?: StoryRuntimeVisualSemanticAssertionsDefinition`');
    expect(docSource).toContain('### Visual semantic assertions');
    expect(docSource).toContain('- `forbiddenVisibleText?: string[]`');
    expect(docSource).toContain('- `forbiddenVisibleTextPatterns?: string[]`');
    expect(docSource).toContain('- `allowedDefaultForbiddenVisibleText?: string[]`');
    expect(docSource).toContain('- `requiredViewportTestIds?: string[]`');
    expect(docSource).toContain('- `requiredViewerLocalDateTimeTestIds?: string[]`');
    expect(docSource).toContain('- `primaryActionTestIds?: string[]`');
    expect(contractSource).toContain('prominentActionScopeTestIds?: readonly string[];');
    expect(docSource).toContain('- `prominentActionScopeTestIds?: string[]`');
    expect(docSource).toContain('unique visible scope container');
    expect(docSource).toContain('- `maxProminentActions?: number`');
    expect(docSource).toContain('surface::target');
    expect(docSource).toContain('### Visual review');
    expect(docSource).toContain('- `scenes: StoryRuntimeVisualReviewSceneDefinition[]`');
    expect(docSource).toContain('- `agentTask?: StoryRuntimeVisualReviewAgentTaskDefinition`');
    expect(docSource).toContain('### Agent task turn');
    expect(docSource).toContain('- `prompt: string`');
    expect(docSource).toContain('- `expectedToken: string`');
    expect(docSource).toContain('- `expectedArtifactPath: string`');
    expect(docSource).toContain('- `minAgentMessages?: number`');
    expect(docSource).toContain('### Agent task flow');
    expect(docSource).toContain('- `turnOne: StoryRuntimeAgentTaskTurnDefinition`');
    expect(docSource).toContain('- `turnTwo: StoryRuntimeAgentTaskTurnDefinition`');
    expect(docSource).toContain('### Visual review Agent task');
    expect(docSource).toContain('- `taskTitlePrefix: string`');
    expect(docSource).toContain('- `expectedTokenPrefix: string`');
    expect(docSource).toContain('- `artifactNamePrefix: string`');
    expect(docSource).toContain('- `artifactExtension: string`');
    expect(docSource).toContain('- `promptIntro: string`');
    expect(docSource).toContain('- `artifactBodyLines: string[]`');
    expect(docSource).toContain('- if `note` is present, it must be non-empty');
    expect(docSource).toContain('- committed stories may live under `e2e/stories/backend-real/` or `e2e/stories/mock-lane/`');
  });
});
