#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${ROOT_DIR}/scripts/cluster-deploy/lib.sh"
source "${ROOT_DIR}/scripts/lib/k8s-external-services.sh"
source "${ROOT_DIR}/scripts/lib/preset-common.sh"

derive_ws_base_from_http_base() {
  local value="${1:-}"
  if [[ -z "${value}" ]]; then
    return 0
  fi
  if [[ "${value}" == ws://* || "${value}" == wss://* ]]; then
    printf '%s' "${value}"
    return 0
  fi
  case "${value}" in
    http://*)
      printf 'ws://%s' "${value#http://}"
      ;;
    https://*)
      printf 'wss://%s' "${value#https://}"
      ;;
    *)
      printf '%s' "${value}"
      ;;
  esac
}

ensure_dirs
mkdir -p "${RELEASE_ROOT}/env"
ensure_operator_registry_env
load_registry_env
require_version_images
SITE_ENV_EXAMPLE="${RELEASE_ROOT}/env/site.env.example"
SITE_ENV="${RELEASE_ROOT}/env/site.env"
[[ -f "${SITE_ENV_EXAMPLE}" ]] || die "missing site env example at ${SITE_ENV_EXAMPLE}"
if [[ ! -f "${SITE_ENV}" ]]; then
  cp "${SITE_ENV_EXAMPLE}" "${SITE_ENV}"
fi

set -a
load_agentsmith_presets "${ROOT_DIR}"
source "${SITE_ENV}"
apply_non_environment_preset_defaults
apply_preset_endpoint_defaults
MBOS_AGENT_JUICEFS_MOUNT_OPTIONS="${MBOS_AGENT_JUICEFS_MOUNT_OPTIONS:-}"
if [[ -z "${SYSTEM_ADMIN_SESSION_COOKIE_SECURE:-}" ]]; then
  if [[ "${PUBLIC_WEB_BASE_URL}" == https://* ]]; then
    SYSTEM_ADMIN_SESSION_COOKIE_SECURE=true
  else
    SYSTEM_ADMIN_SESSION_COOKIE_SECURE=false
  fi
fi
COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL="${COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL:-${SANDBOX_MANAGER_PUBLIC_BASE_URL}}"
COMPOSE_RUNTIME_NO_PROXY="$(compose_runtime_no_proxy \
  "${SANDBOX_MANAGER_INGRESS_HOST:-}" \
  "${COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL:-}" \
  "${SANDBOX_MANAGER_PUBLIC_BASE_URL:-}")"
COMPOSE_INTERNAL_SANDBOX_MANAGER_WS_BASE_URL="$(derive_ws_base_from_http_base "${COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL}")"
K8S_EXTERNAL_API_BASE_URL="${K8S_EXTERNAL_API_BASE_URL:-${PUBLIC_API_BASE_URL}}"
K8S_EXTERNAL_API_WS_BASE_URL="$(derive_ws_base_from_http_base "${K8S_EXTERNAL_API_BASE_URL}")"
set +a

if [[ -n "${K8S_JUICEFS_MOUNT_IMAGE:-}" ]]; then
  INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE="${K8S_JUICEFS_MOUNT_IMAGE}"
fi

for required_nonempty_key in \
  PUBLIC_WEB_BASE_URL \
  PUBLIC_API_BASE_URL \
  PUBLIC_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_API_BASE_URL \
  COMPOSE_INTERNAL_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL \
  HOST_LOCAL_POSTGRES_HOST \
  HOST_LOCAL_POSTGRES_PORT \
  HOST_LOCAL_MINIO_ENDPOINT \
  CLIENT_PUBLIC_POSTGRES_HOST \
  CLIENT_PUBLIC_POSTGRES_PORT \
  CLIENT_PUBLIC_MINIO_ENDPOINT \
  K8S_EXTERNAL_POSTGRES_HOST \
  K8S_EXTERNAL_MINIO_HOST \
  SANDBOX_MANAGER_PUBLIC_BASE_URL \
  COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL \
  INTERNAL_AGENT_WORKLOAD_NODE_SELECTOR_JSON \
  INTERNAL_AGENT_WORKLOAD_TOLERATIONS_JSON \
  SANDBOX_MANAGER_NODE_SELECTOR_JSON \
  SANDBOX_MANAGER_TOLERATIONS_JSON; do
  if [[ -z "${!required_nonempty_key:-}" ]]; then
    die "missing required site.env value: ${required_nonempty_key}"
  fi
done

validate_http_url() {
  python3 - "$1" "$2" <<'PY'
import sys
from urllib.parse import urlparse
key, value = sys.argv[1], sys.argv[2]
parsed = urlparse(value)
if parsed.scheme not in {"http", "https"} or not parsed.netloc:
    raise SystemExit(f"invalid {key}: expected absolute http(s) URL, got {value}")
PY
}

for url_key in \
  PUBLIC_WEB_BASE_URL \
  PUBLIC_API_BASE_URL \
  PUBLIC_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_API_BASE_URL \
  COMPOSE_INTERNAL_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL \
  HOST_LOCAL_MINIO_ENDPOINT \
  CLIENT_PUBLIC_MINIO_ENDPOINT \
  COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL \
  SANDBOX_MANAGER_PUBLIC_BASE_URL; do
  validate_http_url "${url_key}" "${!url_key}"
done

if [[ "${SYSTEM_ADMIN_SESSION_COOKIE_SECURE}" == "true" && "${PUBLIC_WEB_BASE_URL}" != https://* ]]; then
  die "SYSTEM_ADMIN_SESSION_COOKIE_SECURE=true requires PUBLIC_WEB_BASE_URL to use https"
fi

cat > "${RELEASE_ROOT}/env/base.env" <<EOF
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
MONGO_DB=${MONGO_DB}
MONGO_PORT=${MONGO_PORT}
REDIS_PORT=${REDIS_PORT}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=${MINIO_BUCKET}
MINIO_API_PORT=${MINIO_API_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_DB=${KEYCLOAK_DB}
KEYCLOAK_PORT=${KEYCLOAK_PORT}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
PUBLIC_WEB_BASE_URL=${PUBLIC_WEB_BASE_URL}
PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
PUBLIC_KEYCLOAK_BASE_URL=${PUBLIC_KEYCLOAK_BASE_URL}
API_PORT=${API_PORT}
WEB_PORT=${WEB_PORT}
SYSTEM_ADMIN_USERNAME=${SYSTEM_ADMIN_USERNAME}
SYSTEM_ADMIN_PASSWORD=${SYSTEM_ADMIN_PASSWORD}
MBOS_DEFAULT_WORKSPACE_ID=${MBOS_DEFAULT_WORKSPACE_ID}
MBOS_DEFAULT_WORKSPACE_NAME=${MBOS_DEFAULT_WORKSPACE_NAME}
MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL=${MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL}
PRESET_ENDPOINT_API_KEY=${PRESET_ENDPOINT_API_KEY}
PRESET_ENDPOINT_MODEL=${PRESET_ENDPOINT_MODEL}
MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS=${MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS:-120}
PRESET_ENDPOINT_TIMEOUT_SECONDS=${PRESET_ENDPOINT_TIMEOUT_SECONDS}
PRESET_PROJECT_NAME=${PRESET_PROJECT_NAME}
PRESET_CREDENTIAL_NAME=${PRESET_CREDENTIAL_NAME}
PRESET_ANTHROPIC_ENDPOINT_NAME=${PRESET_ANTHROPIC_ENDPOINT_NAME}
PRESET_OPENAI_ENDPOINT_NAME=${PRESET_OPENAI_ENDPOINT_NAME}
PRESET_EXTERNAL_AGENT_NAME=${PRESET_EXTERNAL_AGENT_NAME}
PRESET_INTERNAL_AGENT_NAME=${PRESET_INTERNAL_AGENT_NAME}
PRESET_ENDPOINT_MAX_CONTEXT_TOKENS=${PRESET_ENDPOINT_MAX_CONTEXT_TOKENS}
PRESET_ENDPOINT_MAX_OUTPUT_TOKENS=${PRESET_ENDPOINT_MAX_OUTPUT_TOKENS}
PRESET_ANTHROPIC_ENDPOINT_BASE_URL=${PRESET_ANTHROPIC_ENDPOINT_BASE_URL}
PRESET_ANTHROPIC_ENDPOINT_PROTOCOL=${PRESET_ANTHROPIC_ENDPOINT_PROTOCOL}
PRESET_OPENAI_ENDPOINT_BASE_URL=${PRESET_OPENAI_ENDPOINT_BASE_URL}
PRESET_OPENAI_ENDPOINT_PROTOCOL=${PRESET_OPENAI_ENDPOINT_PROTOCOL}
MBOS_AGENT_CODEX_YOLO=${MBOS_AGENT_CODEX_YOLO}
NO_PROXY=${COMPOSE_RUNTIME_NO_PROXY}
no_proxy=${COMPOSE_RUNTIME_NO_PROXY}
EOF

cat > "${RELEASE_ROOT}/env/api.env" <<EOF
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/admin
MONGO_DB_NAME=${MONGO_DB}
SYSTEM_WORKSPACE_REGISTRY_MODE=${SYSTEM_WORKSPACE_REGISTRY_MODE}
REDIS_URL=redis://redis:6379
PORT=20000
INTERNAL_API_BASE_URL=${COMPOSE_INTERNAL_API_BASE_URL}
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET=${MINIO_BUCKET}
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
FILE_LIBRARY_CLIENT_POSTGRES_HOST=${CLIENT_PUBLIC_POSTGRES_HOST}
FILE_LIBRARY_CLIENT_POSTGRES_PORT=${CLIENT_PUBLIC_POSTGRES_PORT}
FILE_LIBRARY_CLIENT_MINIO_ENDPOINT=${CLIENT_PUBLIC_MINIO_ENDPOINT}
EXTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE=${CLIENT_PUBLIC_POSTGRES_HOST}
EXTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE=${CLIENT_PUBLIC_POSTGRES_PORT}
EXTERNAL_AGENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE=${CLIENT_PUBLIC_MINIO_ENDPOINT}
INTERNAL_KEYCLOAK_BASE_URL=${COMPOSE_INTERNAL_KEYCLOAK_BASE_URL}
KEYCLOAK_ISSUER_URL=${PUBLIC_KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
AGENT_EXECUTION_HTTP_BASE_URL=${K8S_EXTERNAL_API_BASE_URL}
AGENT_EXECUTION_WS_BASE_URL=${K8S_EXTERNAL_API_WS_BASE_URL}
EXTERNAL_AGENT_EXECUTION_HTTP_BASE_URL=${PUBLIC_API_BASE_URL}
SANDBOX_MANAGER_URL=${COMPOSE_INTERNAL_SANDBOX_MANAGER_BASE_URL}
SANDBOX_SERVICE_KEY=${SANDBOX_SERVICE_KEY}
MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS=${MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS:-120}
MBOS_UNIVERSAL_PROXY_BASE_URL=${COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL}
INTERNAL_AGENT_DEFAULT_CPU_REQUEST=${INTERNAL_AGENT_DEFAULT_CPU_REQUEST}
INTERNAL_AGENT_DEFAULT_CPU_LIMIT=${INTERNAL_AGENT_DEFAULT_CPU_LIMIT}
INTERNAL_AGENT_DEFAULT_MEMORY_REQUEST=${INTERNAL_AGENT_DEFAULT_MEMORY_REQUEST}
INTERNAL_AGENT_DEFAULT_MEMORY_LIMIT=${INTERNAL_AGENT_DEFAULT_MEMORY_LIMIT}
EOF

cat > "${RELEASE_ROOT}/env/web.env" <<EOF
MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/admin
MONGO_DB_NAME=${MONGO_DB}
SYSTEM_WORKSPACE_REGISTRY_MODE=${SYSTEM_WORKSPACE_REGISTRY_MODE}
INTERNAL_KEYCLOAK_BASE_URL=${COMPOSE_INTERNAL_KEYCLOAK_BASE_URL}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
SYSTEM_ADMIN_SESSION_COOKIE_SECURE=${SYSTEM_ADMIN_SESSION_COOKIE_SECURE}
NEXT_PUBLIC_API_BASE=${PUBLIC_API_BASE_URL}
NEXT_PUBLIC_KEYCLOAK_URL=${PUBLIC_KEYCLOAK_BASE_URL}
NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
NEXT_PUBLIC_USE_MSW=false
EOF

cat > "${RELEASE_ROOT}/env/keycloak.env" <<EOF
PUBLIC_KEYCLOAK_BASE_URL=${PUBLIC_KEYCLOAK_BASE_URL}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
INTEGRATION_PUBLIC_WEB_BASES=${INTEGRATION_PUBLIC_WEB_BASES}
INTEGRATION_DEV_ADMIN_USERNAME=${INTEGRATION_DEV_ADMIN_USERNAME}
INTEGRATION_DEV_ADMIN_PASSWORD=${INTEGRATION_DEV_ADMIN_PASSWORD}
INTEGRATION_USER_USERNAME=${INTEGRATION_USER_USERNAME}
INTEGRATION_USER_PASSWORD=${INTEGRATION_USER_PASSWORD}
INTEGRATION_MEMBER_USERNAME=${INTEGRATION_MEMBER_USERNAME}
INTEGRATION_MEMBER_PASSWORD=${INTEGRATION_MEMBER_PASSWORD}
EOF

cat > "${RELEASE_ROOT}/env/internal.env" <<EOF
INTERNAL_AGENT_K8S_NAMESPACE=${INTERNAL_AGENT_K8S_NAMESPACE}
INTERNAL_AGENT_IMAGE=${K8S_RUNNER_IMAGE}
INTERNAL_AGENT_JUICEFS_CSI_DRIVER=${INTERNAL_AGENT_JUICEFS_CSI_DRIVER}
INTERNAL_AGENT_WORKSPACE_CAPACITY=${INTERNAL_AGENT_WORKSPACE_CAPACITY}
INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME=${INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME}
INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS=${INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS}
INTERNAL_AGENT_JUICEFS_SUBDIR=${INTERNAL_AGENT_JUICEFS_SUBDIR}
INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT=${INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT}
INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE=${INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE}
INTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE=$(k8s_external_postgres_fqdn "${INTERNAL_AGENT_K8S_NAMESPACE}")
INTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE=5432
INTERNAL_AGENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE=http://$(k8s_external_minio_fqdn "${INTERNAL_AGENT_K8S_NAMESPACE}"):9000
INTERNAL_AGENT_DEFAULT_CPU_REQUEST=${INTERNAL_AGENT_DEFAULT_CPU_REQUEST}
INTERNAL_AGENT_DEFAULT_CPU_LIMIT=${INTERNAL_AGENT_DEFAULT_CPU_LIMIT}
INTERNAL_AGENT_DEFAULT_MEMORY_REQUEST=${INTERNAL_AGENT_DEFAULT_MEMORY_REQUEST}
INTERNAL_AGENT_DEFAULT_MEMORY_LIMIT=${INTERNAL_AGENT_DEFAULT_MEMORY_LIMIT}
INTERNAL_AGENT_WORKLOAD_NODE_SELECTOR_JSON='${INTERNAL_AGENT_WORKLOAD_NODE_SELECTOR_JSON}'
INTERNAL_AGENT_WORKLOAD_TOLERATIONS_JSON='${INTERNAL_AGENT_WORKLOAD_TOLERATIONS_JSON}'
EOF

cat > "${RELEASE_ROOT}/env/runner.env" <<EOF
MBOS_API_BASE=${COMPOSE_INTERNAL_API_BASE_URL}
MBOS_AGENT_BUILTIN_SKILLS_DIR=${MBOS_AGENT_BUILTIN_SKILLS_DIR}
MBOS_AGENT_JUICEFS_MOUNT_OPTIONS=${MBOS_AGENT_JUICEFS_MOUNT_OPTIONS}
MBOS_AGENT_CODEX_YOLO=${MBOS_AGENT_CODEX_YOLO}
PRESET_ENDPOINT_API_KEY=${PRESET_ENDPOINT_API_KEY}
EOF

if [[ ! -f "${RELEASE_ROOT}/env/runner-runtime.env" ]]; then
  cat > "${RELEASE_ROOT}/env/runner-runtime.env" <<'EOF'
# Generated by bootstrap.sh after preset external agent provisioning.
# Operators must not edit this file manually.
MBOS_AGENT_WS_URL=
MBOS_AGENT_KEY=
EOF
fi

log "render-env ok"
