#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ "$(basename "${SCRIPT_DIR}")" == "demo-deploy" ]]; then
  ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
else
  ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
fi
source "${ROOT_DIR}/scripts/lib/common.sh"
source "${ROOT_DIR}/scripts/lib/k8s-external-services.sh"

ensure_dirs
mkdir -p "${RELEASE_ROOT}/env"

SITE_ENV_EXAMPLE="${RELEASE_ROOT}/env/site.env.example"
SITE_ENV="${RELEASE_ROOT}/env/site.env"
[[ -f "${SITE_ENV_EXAMPLE}" ]] || die "missing site env example at ${SITE_ENV_EXAMPLE}"
if [[ ! -f "${SITE_ENV}" ]]; then
  cp "${SITE_ENV_EXAMPLE}" "${SITE_ENV}"
fi

for deprecated_key in KEYCLOAK_INTERNAL_BASE_URL KEYCLOAK_PUBLIC_BASE_URL MBOS_API_BASE MBOS_DEFAULT_WORKSPACE_ADMIN_USER_ID MBOS_INTEGRATION_USER_ID INTERNAL_API_BASE_URL INTERNAL_KEYCLOAK_BASE_URL FILE_LIBRARY_POSTGRES_PUBLIC_HOST FILE_LIBRARY_POSTGRES_PUBLIC_PORT FILE_LIBRARY_MINIO_PUBLIC_ENDPOINT EXTERNAL_AGENT_EXECUTION_HTTP_BASE_URL AGENT_EXECUTION_HTTP_BASE_URL AGENT_EXECUTION_WS_BASE_URL SANDBOX_MANAGER_URL INTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE INTERNAL_AGENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE; do
  if grep -Eq "^[[:space:]]*${deprecated_key}=" "${SITE_ENV}"; then
    die "deprecated site.env key detected: ${deprecated_key}; update ${SITE_ENV} to deployment-spec-v1"
  fi
done

set -a
# shellcheck disable=SC1090
source "${SITE_ENV}"
set +a

declare -A SITE_ENV_DECLARED=()
while IFS= read -r raw_line || [[ -n "${raw_line}" ]]; do
  line="${raw_line#"${raw_line%%[![:space:]]*}"}"
  [[ -z "${line}" || "${line}" == \#* || "${line}" != *=* ]] && continue
  key="${line%%=*}"
  SITE_ENV_DECLARED["${key}"]=1
done < "${SITE_ENV}"

for required_key in \
  PUBLIC_WEB_BASE_URL \
  PUBLIC_API_BASE_URL \
  PUBLIC_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_API_BASE_URL \
  COMPOSE_INTERNAL_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL \
  HOST_LOCAL_POSTGRES_HOST \
  HOST_LOCAL_POSTGRES_PORT \
  HOST_LOCAL_MINIO_ENDPOINT \
  CLIENT_PUBLIC_POSTGRES_HOST \
  CLIENT_PUBLIC_POSTGRES_PORT \
  CLIENT_PUBLIC_MINIO_ENDPOINT \
  MBOS_DEMO_PROJECT_NAME \
  MBOS_DEMO_CREDENTIAL_NAME \
  MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME \
  MBOS_DEMO_OPENAI_ENDPOINT_NAME \
  MBOS_DEMO_EXTERNAL_AGENT_NAME \
  MBOS_DEMO_INTERNAL_AGENT_NAME \
  MBOS_DEMO_MODEL_CONTEXT_TOKENS \
  MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS \
  MBOS_AGENT_CODEX_YOLO \
  MBOS_AGENT_JUICEFS_MOUNT_OPTIONS \
  SANDBOX_HOST_PORT; do
  if [[ -z "${SITE_ENV_DECLARED[${required_key}]:-}" ]]; then
    die "missing required site.env key: ${required_key}"
  fi
done

for required_nonempty_key in \
  PUBLIC_WEB_BASE_URL \
  PUBLIC_API_BASE_URL \
  PUBLIC_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_API_BASE_URL \
  COMPOSE_INTERNAL_KEYCLOAK_BASE_URL \
  HOST_LOCAL_POSTGRES_HOST \
  HOST_LOCAL_POSTGRES_PORT \
  HOST_LOCAL_MINIO_ENDPOINT \
  CLIENT_PUBLIC_POSTGRES_HOST \
  CLIENT_PUBLIC_POSTGRES_PORT \
  CLIENT_PUBLIC_MINIO_ENDPOINT \
  MBOS_DEMO_PROJECT_NAME \
  MBOS_DEMO_CREDENTIAL_NAME \
  MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME \
  MBOS_DEMO_OPENAI_ENDPOINT_NAME \
  MBOS_DEMO_EXTERNAL_AGENT_NAME \
  MBOS_DEMO_INTERNAL_AGENT_NAME \
  MBOS_DEMO_MODEL_CONTEXT_TOKENS \
  MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS \
  MBOS_AGENT_CODEX_YOLO \
  SANDBOX_HOST_PORT; do
  if [[ -z "${!required_nonempty_key:-}" ]]; then
    die "missing required site.env value: ${required_nonempty_key}"
  fi
done

validate_http_url() {
  local key="$1"
  local value="$2"
  python3 - "$key" "$value" <<'PY'
import sys
from urllib.parse import urlparse

key, value = sys.argv[1], sys.argv[2]
parsed = urlparse(value)
if parsed.scheme not in {"http", "https"} or not parsed.netloc:
    raise SystemExit(f"invalid {key}: expected absolute http(s) URL, got {value}")
PY
}

for url_key in \
  PUBLIC_WEB_BASE_URL \
  PUBLIC_API_BASE_URL \
  PUBLIC_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_API_BASE_URL \
  COMPOSE_INTERNAL_KEYCLOAK_BASE_URL \
  COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL \
  HOST_LOCAL_MINIO_ENDPOINT \
  CLIENT_PUBLIC_MINIO_ENDPOINT; do
  validate_http_url "${url_key}" "${!url_key}"
done

bash "${RELEASE_SCRIPT_DIR}/resolve-runtime-addresses.sh"

set -a
# shellcheck disable=SC1090
source "${RELEASE_ROOT}/env/runtime-addresses.env"
set +a

for resolved_key in \
  RESOLVED_RUNNER_HTTP_BASE_URL \
  RESOLVED_RUNNER_WS_BASE_URL \
  RESOLVED_SANDBOX_MANAGER_URL \
  RESOLVED_KIND_GATEWAY_HOST \
  RESOLVED_KIND_HTTP_BASE_URL \
  RESOLVED_KIND_WS_BASE_URL \
  RESOLVED_LOCAL_FILE_LIBRARY_POSTGRES_HOST \
  RESOLVED_LOCAL_FILE_LIBRARY_POSTGRES_PORT \
  RESOLVED_LOCAL_FILE_LIBRARY_MINIO_ENDPOINT; do
  if [[ -z "${!resolved_key:-}" ]]; then
    die "missing resolved runtime address: ${resolved_key}"
  fi
done

public_web_host="$(python3 - "${PUBLIC_WEB_BASE_URL}" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or '')
PY
)"
public_api_host="$(python3 - "${PUBLIC_API_BASE_URL}" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or '')
PY
)"
public_keycloak_host="$(python3 - "${PUBLIC_KEYCLOAK_BASE_URL}" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or '')
PY
)"
client_minio_host="$(python3 - "${CLIENT_PUBLIC_MINIO_ENDPOINT}" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or '')
PY
)"

is_local_host() {
  case "$1" in
    localhost|127.0.0.1|::1) return 0 ;;
    *) return 1 ;;
  esac
}

if ! is_local_host "${public_web_host}" && is_local_host "${public_api_host}"; then
  die "PUBLIC_API_BASE_URL points to a local host while PUBLIC_WEB_BASE_URL is public"
fi

if ! is_local_host "${public_web_host}" && is_local_host "${public_keycloak_host}"; then
  die "PUBLIC_KEYCLOAK_BASE_URL points to a local host while PUBLIC_WEB_BASE_URL is public"
fi

if ! is_local_host "${public_web_host}" && is_local_host "${CLIENT_PUBLIC_POSTGRES_HOST}"; then
  die "CLIENT_PUBLIC_POSTGRES_HOST points to a local host while PUBLIC_WEB_BASE_URL is public"
fi

if ! is_local_host "${public_web_host}" && is_local_host "${client_minio_host}"; then
  die "CLIENT_PUBLIC_MINIO_ENDPOINT points to a local host while PUBLIC_WEB_BASE_URL is public"
fi

cat > "${RELEASE_ROOT}/env/base.env" <<EOF
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
MONGO_DB=${MONGO_DB}
MONGO_PORT=${MONGO_PORT}
REDIS_PORT=${REDIS_PORT}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=${MINIO_BUCKET}
MINIO_API_PORT=${MINIO_API_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_DB=${KEYCLOAK_DB}
KEYCLOAK_PORT=${KEYCLOAK_PORT}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
PUBLIC_WEB_BASE_URL=${PUBLIC_WEB_BASE_URL}
PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
PUBLIC_KEYCLOAK_BASE_URL=${PUBLIC_KEYCLOAK_BASE_URL}
API_PORT=${API_PORT}
WEB_PORT=${WEB_PORT}
SYSTEM_ADMIN_USERNAME=${SYSTEM_ADMIN_USERNAME}
SYSTEM_ADMIN_PASSWORD=${SYSTEM_ADMIN_PASSWORD}
MBOS_DEFAULT_WORKSPACE_ID=${MBOS_DEFAULT_WORKSPACE_ID}
MBOS_DEFAULT_WORKSPACE_NAME=${MBOS_DEFAULT_WORKSPACE_NAME}
MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL=${MBOS_DEFAULT_WORKSPACE_ADMIN_EMAIL}
DEPLOY_ENDPOINT_API_KEY=${DEPLOY_ENDPOINT_API_KEY}
DEPLOY_ANTHROPIC_BASE_URL=${DEPLOY_ANTHROPIC_BASE_URL}
DEPLOY_OPENAI_BASE_URL=${DEPLOY_OPENAI_BASE_URL}
DEPLOY_ENDPOINT_MODEL=${DEPLOY_ENDPOINT_MODEL}
MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS=${MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS:-120}
MBOS_DEMO_ENDPOINT_TIMEOUT_SECONDS=${MBOS_DEMO_ENDPOINT_TIMEOUT_SECONDS:-900}
MBOS_DEMO_PROJECT_NAME=${MBOS_DEMO_PROJECT_NAME}
MBOS_DEMO_CREDENTIAL_NAME=${MBOS_DEMO_CREDENTIAL_NAME}
MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME=${MBOS_DEMO_ANTHROPIC_ENDPOINT_NAME}
MBOS_DEMO_OPENAI_ENDPOINT_NAME=${MBOS_DEMO_OPENAI_ENDPOINT_NAME}
MBOS_DEMO_EXTERNAL_AGENT_NAME=${MBOS_DEMO_EXTERNAL_AGENT_NAME}
MBOS_DEMO_INTERNAL_AGENT_NAME=${MBOS_DEMO_INTERNAL_AGENT_NAME}
MBOS_DEMO_MODEL_CONTEXT_TOKENS=${MBOS_DEMO_MODEL_CONTEXT_TOKENS}
MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS=${MBOS_DEMO_MODEL_MAX_OUTPUT_TOKENS}
MBOS_AGENT_CODEX_YOLO=${MBOS_AGENT_CODEX_YOLO}
EOF

cat > "${RELEASE_ROOT}/env/api.env" <<EOF
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/admin
MONGO_DB_NAME=${MONGO_DB}
SYSTEM_WORKSPACE_REGISTRY_MODE=${SYSTEM_WORKSPACE_REGISTRY_MODE}
REDIS_URL=redis://redis:6379
PORT=20000
INTERNAL_API_BASE_URL=${COMPOSE_INTERNAL_API_BASE_URL}
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET=${MINIO_BUCKET}
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
FILE_LIBRARY_CLIENT_POSTGRES_HOST=${CLIENT_PUBLIC_POSTGRES_HOST}
FILE_LIBRARY_CLIENT_POSTGRES_PORT=${CLIENT_PUBLIC_POSTGRES_PORT}
FILE_LIBRARY_CLIENT_MINIO_ENDPOINT=${CLIENT_PUBLIC_MINIO_ENDPOINT}
EXTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE=${CLIENT_PUBLIC_POSTGRES_HOST}
EXTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE=${CLIENT_PUBLIC_POSTGRES_PORT}
EXTERNAL_AGENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE=${CLIENT_PUBLIC_MINIO_ENDPOINT}
INTERNAL_KEYCLOAK_BASE_URL=${COMPOSE_INTERNAL_KEYCLOAK_BASE_URL}
KEYCLOAK_ISSUER_URL=${PUBLIC_KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
AGENT_EXECUTION_HTTP_BASE_URL=${RESOLVED_KIND_HTTP_BASE_URL}
SYSTEM_ADMIN_USERNAME=${SYSTEM_ADMIN_USERNAME}
SYSTEM_ADMIN_PASSWORD=${SYSTEM_ADMIN_PASSWORD}
AGENT_EXECUTION_WS_BASE_URL=${RESOLVED_KIND_WS_BASE_URL}
EXTERNAL_AGENT_EXECUTION_HTTP_BASE_URL=${RESOLVED_RUNNER_HTTP_BASE_URL}
SANDBOX_MANAGER_URL=${RESOLVED_SANDBOX_MANAGER_URL}
SANDBOX_SERVICE_KEY=${SANDBOX_SERVICE_KEY}
SANDBOX_HOST_PORT=${SANDBOX_HOST_PORT}
MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS=${MBOS_ENDPOINT_PROXY_DEFAULT_TIMEOUT_SECONDS:-120}
MBOS_UNIVERSAL_PROXY_BASE_URL=${COMPOSE_INTERNAL_UNIVERSAL_PROXY_BASE_URL}
EOF

cat > "${RELEASE_ROOT}/env/web.env" <<EOF
MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/admin
MONGO_DB_NAME=${MONGO_DB}
SYSTEM_WORKSPACE_REGISTRY_MODE=${SYSTEM_WORKSPACE_REGISTRY_MODE}
INTERNAL_KEYCLOAK_BASE_URL=${COMPOSE_INTERNAL_KEYCLOAK_BASE_URL}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
SYSTEM_ADMIN_SESSION_COOKIE_SECURE=${SYSTEM_ADMIN_SESSION_COOKIE_SECURE}
NEXT_PUBLIC_API_BASE=${PUBLIC_API_BASE_URL}
NEXT_PUBLIC_KEYCLOAK_URL=${PUBLIC_KEYCLOAK_BASE_URL}
NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
NEXT_PUBLIC_USE_MSW=false
EOF

cat > "${RELEASE_ROOT}/env/keycloak.env" <<EOF
PUBLIC_KEYCLOAK_BASE_URL=${PUBLIC_KEYCLOAK_BASE_URL}
KEYCLOAK_REALM=${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
INTEGRATION_PUBLIC_WEB_BASES=${INTEGRATION_PUBLIC_WEB_BASES}
INTEGRATION_DEV_ADMIN_USERNAME=${INTEGRATION_DEV_ADMIN_USERNAME}
INTEGRATION_DEV_ADMIN_PASSWORD=${INTEGRATION_DEV_ADMIN_PASSWORD}
INTEGRATION_USER_USERNAME=${INTEGRATION_USER_USERNAME}
INTEGRATION_USER_PASSWORD=${INTEGRATION_USER_PASSWORD}
INTEGRATION_MEMBER_USERNAME=${INTEGRATION_MEMBER_USERNAME}
INTEGRATION_MEMBER_PASSWORD=${INTEGRATION_MEMBER_PASSWORD}
EOF

cat > "${RELEASE_ROOT}/env/internal.env" <<EOF
INTERNAL_AGENT_K8S_NAMESPACE=${INTERNAL_AGENT_K8S_NAMESPACE}
INTERNAL_AGENT_JUICEFS_CSI_DRIVER=${INTERNAL_AGENT_JUICEFS_CSI_DRIVER}
INTERNAL_AGENT_WORKSPACE_CAPACITY=${INTERNAL_AGENT_WORKSPACE_CAPACITY}
INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME=${INTERNAL_AGENT_JUICEFS_STORAGE_CLASS_NAME}
INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS=${INTERNAL_AGENT_JUICEFS_MOUNT_OPTIONS}
INTERNAL_AGENT_JUICEFS_SUBDIR=${INTERNAL_AGENT_JUICEFS_SUBDIR}
INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT=${INTERNAL_AGENT_JUICEFS_MOUNT_SERVICE_ACCOUNT}
INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE=${INTERNAL_AGENT_JUICEFS_MOUNT_IMAGE}
INTERNAL_AGENT_JUICEFS_META_HOST_OVERRIDE=$(k8s_external_postgres_fqdn "${INTERNAL_AGENT_K8S_NAMESPACE}")
INTERNAL_AGENT_JUICEFS_META_PORT_OVERRIDE=5432
INTERNAL_AGENT_JUICEFS_STORAGE_ENDPOINT_OVERRIDE=http://$(k8s_external_minio_fqdn "${INTERNAL_AGENT_K8S_NAMESPACE}"):9000
EOF

cat > "${RELEASE_ROOT}/env/runner.env" <<EOF
MBOS_API_BASE=${COMPOSE_INTERNAL_API_BASE_URL}
MBOS_AGENT_BUILTIN_SKILLS_DIR=${MBOS_AGENT_BUILTIN_SKILLS_DIR}
MBOS_AGENT_JUICEFS_MOUNT_OPTIONS=${MBOS_AGENT_JUICEFS_MOUNT_OPTIONS}
MBOS_AGENT_CODEX_YOLO=${MBOS_AGENT_CODEX_YOLO}
DEPLOY_ENDPOINT_API_KEY=${DEPLOY_ENDPOINT_API_KEY}
EOF

if [[ ! -f "${RELEASE_ROOT}/env/runner-runtime.env" ]]; then
  cat > "${RELEASE_ROOT}/env/runner-runtime.env" <<'EOF'
# Generated by bootstrap.sh after preset external agent provisioning.
# Operators must not edit this file manually.
MBOS_AGENT_WS_URL=
MBOS_AGENT_KEY=
EOF
fi

log "render-env ok"
