kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agentsmith
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
      endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2
    extraPortMappings:
      - containerPort: 30080
        hostPort: 29180
        protocol: TCP
